// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_workload_eviction

import (
	context "context"

	workload_eviction "github.com/castai/terraform-provider-castai/castai/sdk/workload_eviction"

	http "net/http"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockClientInterface is an autogenerated mock type for the ClientInterface type
type MockClientInterface struct {
	mock.Mock
}

type MockClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientInterface) EXPECT() *MockClientInterface_Expecter {
	return &MockClientInterface_Expecter{mock: &_m.Mock}
}

// EvictorAPIGetConfig provides a mock function with given fields: ctx, clusterId, reqEditors
func (_m *MockClientInterface) EvictorAPIGetConfig(ctx context.Context, clusterId string, reqEditors ...workload_eviction.RequestEditorFn) (*http.Response, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, clusterId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for EvictorAPIGetConfig")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...workload_eviction.RequestEditorFn) (*http.Response, error)); ok {
		return rf(ctx, clusterId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...workload_eviction.RequestEditorFn) *http.Response); ok {
		r0 = rf(ctx, clusterId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...workload_eviction.RequestEditorFn) error); ok {
		r1 = rf(ctx, clusterId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_EvictorAPIGetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvictorAPIGetConfig'
type MockClientInterface_EvictorAPIGetConfig_Call struct {
	*mock.Call
}

// EvictorAPIGetConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterId string
//   - reqEditors ...workload_eviction.RequestEditorFn
func (_e *MockClientInterface_Expecter) EvictorAPIGetConfig(ctx interface{}, clusterId interface{}, reqEditors ...interface{}) *MockClientInterface_EvictorAPIGetConfig_Call {
	return &MockClientInterface_EvictorAPIGetConfig_Call{Call: _e.mock.On("EvictorAPIGetConfig",
		append([]interface{}{ctx, clusterId}, reqEditors...)...)}
}

func (_c *MockClientInterface_EvictorAPIGetConfig_Call) Run(run func(ctx context.Context, clusterId string, reqEditors ...workload_eviction.RequestEditorFn)) *MockClientInterface_EvictorAPIGetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]workload_eviction.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(workload_eviction.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockClientInterface_EvictorAPIGetConfig_Call) Return(_a0 *http.Response, _a1 error) *MockClientInterface_EvictorAPIGetConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_EvictorAPIGetConfig_Call) RunAndReturn(run func(context.Context, string, ...workload_eviction.RequestEditorFn) (*http.Response, error)) *MockClientInterface_EvictorAPIGetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// EvictorAPIGetEvictorAdvancedConfig provides a mock function with given fields: ctx, clusterId, reqEditors
func (_m *MockClientInterface) EvictorAPIGetEvictorAdvancedConfig(ctx context.Context, clusterId string, reqEditors ...workload_eviction.RequestEditorFn) (*http.Response, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, clusterId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for EvictorAPIGetEvictorAdvancedConfig")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...workload_eviction.RequestEditorFn) (*http.Response, error)); ok {
		return rf(ctx, clusterId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...workload_eviction.RequestEditorFn) *http.Response); ok {
		r0 = rf(ctx, clusterId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...workload_eviction.RequestEditorFn) error); ok {
		r1 = rf(ctx, clusterId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_EvictorAPIGetEvictorAdvancedConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvictorAPIGetEvictorAdvancedConfig'
type MockClientInterface_EvictorAPIGetEvictorAdvancedConfig_Call struct {
	*mock.Call
}

// EvictorAPIGetEvictorAdvancedConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterId string
//   - reqEditors ...workload_eviction.RequestEditorFn
func (_e *MockClientInterface_Expecter) EvictorAPIGetEvictorAdvancedConfig(ctx interface{}, clusterId interface{}, reqEditors ...interface{}) *MockClientInterface_EvictorAPIGetEvictorAdvancedConfig_Call {
	return &MockClientInterface_EvictorAPIGetEvictorAdvancedConfig_Call{Call: _e.mock.On("EvictorAPIGetEvictorAdvancedConfig",
		append([]interface{}{ctx, clusterId}, reqEditors...)...)}
}

func (_c *MockClientInterface_EvictorAPIGetEvictorAdvancedConfig_Call) Run(run func(ctx context.Context, clusterId string, reqEditors ...workload_eviction.RequestEditorFn)) *MockClientInterface_EvictorAPIGetEvictorAdvancedConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]workload_eviction.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(workload_eviction.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockClientInterface_EvictorAPIGetEvictorAdvancedConfig_Call) Return(_a0 *http.Response, _a1 error) *MockClientInterface_EvictorAPIGetEvictorAdvancedConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_EvictorAPIGetEvictorAdvancedConfig_Call) RunAndReturn(run func(context.Context, string, ...workload_eviction.RequestEditorFn) (*http.Response, error)) *MockClientInterface_EvictorAPIGetEvictorAdvancedConfig_Call {
	_c.Call.Return(run)
	return _c
}

// EvictorAPIUpdateConfig provides a mock function with given fields: ctx, clusterId, body, reqEditors
func (_m *MockClientInterface) EvictorAPIUpdateConfig(ctx context.Context, clusterId string, body workload_eviction.Config, reqEditors ...workload_eviction.RequestEditorFn) (*http.Response, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, clusterId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for EvictorAPIUpdateConfig")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, workload_eviction.Config, ...workload_eviction.RequestEditorFn) (*http.Response, error)); ok {
		return rf(ctx, clusterId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, workload_eviction.Config, ...workload_eviction.RequestEditorFn) *http.Response); ok {
		r0 = rf(ctx, clusterId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, workload_eviction.Config, ...workload_eviction.RequestEditorFn) error); ok {
		r1 = rf(ctx, clusterId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_EvictorAPIUpdateConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvictorAPIUpdateConfig'
type MockClientInterface_EvictorAPIUpdateConfig_Call struct {
	*mock.Call
}

// EvictorAPIUpdateConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterId string
//   - body workload_eviction.Config
//   - reqEditors ...workload_eviction.RequestEditorFn
func (_e *MockClientInterface_Expecter) EvictorAPIUpdateConfig(ctx interface{}, clusterId interface{}, body interface{}, reqEditors ...interface{}) *MockClientInterface_EvictorAPIUpdateConfig_Call {
	return &MockClientInterface_EvictorAPIUpdateConfig_Call{Call: _e.mock.On("EvictorAPIUpdateConfig",
		append([]interface{}{ctx, clusterId, body}, reqEditors...)...)}
}

func (_c *MockClientInterface_EvictorAPIUpdateConfig_Call) Run(run func(ctx context.Context, clusterId string, body workload_eviction.Config, reqEditors ...workload_eviction.RequestEditorFn)) *MockClientInterface_EvictorAPIUpdateConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]workload_eviction.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(workload_eviction.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(workload_eviction.Config), variadicArgs...)
	})
	return _c
}

func (_c *MockClientInterface_EvictorAPIUpdateConfig_Call) Return(_a0 *http.Response, _a1 error) *MockClientInterface_EvictorAPIUpdateConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_EvictorAPIUpdateConfig_Call) RunAndReturn(run func(context.Context, string, workload_eviction.Config, ...workload_eviction.RequestEditorFn) (*http.Response, error)) *MockClientInterface_EvictorAPIUpdateConfig_Call {
	_c.Call.Return(run)
	return _c
}

// EvictorAPIUpdateConfigWithBody provides a mock function with given fields: ctx, clusterId, contentType, body, reqEditors
func (_m *MockClientInterface) EvictorAPIUpdateConfigWithBody(ctx context.Context, clusterId string, contentType string, body io.Reader, reqEditors ...workload_eviction.RequestEditorFn) (*http.Response, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, clusterId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for EvictorAPIUpdateConfigWithBody")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...workload_eviction.RequestEditorFn) (*http.Response, error)); ok {
		return rf(ctx, clusterId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...workload_eviction.RequestEditorFn) *http.Response); ok {
		r0 = rf(ctx, clusterId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, ...workload_eviction.RequestEditorFn) error); ok {
		r1 = rf(ctx, clusterId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_EvictorAPIUpdateConfigWithBody_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvictorAPIUpdateConfigWithBody'
type MockClientInterface_EvictorAPIUpdateConfigWithBody_Call struct {
	*mock.Call
}

// EvictorAPIUpdateConfigWithBody is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterId string
//   - contentType string
//   - body io.Reader
//   - reqEditors ...workload_eviction.RequestEditorFn
func (_e *MockClientInterface_Expecter) EvictorAPIUpdateConfigWithBody(ctx interface{}, clusterId interface{}, contentType interface{}, body interface{}, reqEditors ...interface{}) *MockClientInterface_EvictorAPIUpdateConfigWithBody_Call {
	return &MockClientInterface_EvictorAPIUpdateConfigWithBody_Call{Call: _e.mock.On("EvictorAPIUpdateConfigWithBody",
		append([]interface{}{ctx, clusterId, contentType, body}, reqEditors...)...)}
}

func (_c *MockClientInterface_EvictorAPIUpdateConfigWithBody_Call) Run(run func(ctx context.Context, clusterId string, contentType string, body io.Reader, reqEditors ...workload_eviction.RequestEditorFn)) *MockClientInterface_EvictorAPIUpdateConfigWithBody_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]workload_eviction.RequestEditorFn, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(workload_eviction.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(io.Reader), variadicArgs...)
	})
	return _c
}

func (_c *MockClientInterface_EvictorAPIUpdateConfigWithBody_Call) Return(_a0 *http.Response, _a1 error) *MockClientInterface_EvictorAPIUpdateConfigWithBody_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_EvictorAPIUpdateConfigWithBody_Call) RunAndReturn(run func(context.Context, string, string, io.Reader, ...workload_eviction.RequestEditorFn) (*http.Response, error)) *MockClientInterface_EvictorAPIUpdateConfigWithBody_Call {
	_c.Call.Return(run)
	return _c
}

// EvictorAPIUpdateEvictorAdvancedConfig provides a mock function with given fields: ctx, clusterId, body, reqEditors
func (_m *MockClientInterface) EvictorAPIUpdateEvictorAdvancedConfig(ctx context.Context, clusterId string, body workload_eviction.AdvancedConfig, reqEditors ...workload_eviction.RequestEditorFn) (*http.Response, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, clusterId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for EvictorAPIUpdateEvictorAdvancedConfig")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, workload_eviction.AdvancedConfig, ...workload_eviction.RequestEditorFn) (*http.Response, error)); ok {
		return rf(ctx, clusterId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, workload_eviction.AdvancedConfig, ...workload_eviction.RequestEditorFn) *http.Response); ok {
		r0 = rf(ctx, clusterId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, workload_eviction.AdvancedConfig, ...workload_eviction.RequestEditorFn) error); ok {
		r1 = rf(ctx, clusterId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_EvictorAPIUpdateEvictorAdvancedConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvictorAPIUpdateEvictorAdvancedConfig'
type MockClientInterface_EvictorAPIUpdateEvictorAdvancedConfig_Call struct {
	*mock.Call
}

// EvictorAPIUpdateEvictorAdvancedConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterId string
//   - body workload_eviction.AdvancedConfig
//   - reqEditors ...workload_eviction.RequestEditorFn
func (_e *MockClientInterface_Expecter) EvictorAPIUpdateEvictorAdvancedConfig(ctx interface{}, clusterId interface{}, body interface{}, reqEditors ...interface{}) *MockClientInterface_EvictorAPIUpdateEvictorAdvancedConfig_Call {
	return &MockClientInterface_EvictorAPIUpdateEvictorAdvancedConfig_Call{Call: _e.mock.On("EvictorAPIUpdateEvictorAdvancedConfig",
		append([]interface{}{ctx, clusterId, body}, reqEditors...)...)}
}

func (_c *MockClientInterface_EvictorAPIUpdateEvictorAdvancedConfig_Call) Run(run func(ctx context.Context, clusterId string, body workload_eviction.AdvancedConfig, reqEditors ...workload_eviction.RequestEditorFn)) *MockClientInterface_EvictorAPIUpdateEvictorAdvancedConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]workload_eviction.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(workload_eviction.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(workload_eviction.AdvancedConfig), variadicArgs...)
	})
	return _c
}

func (_c *MockClientInterface_EvictorAPIUpdateEvictorAdvancedConfig_Call) Return(_a0 *http.Response, _a1 error) *MockClientInterface_EvictorAPIUpdateEvictorAdvancedConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_EvictorAPIUpdateEvictorAdvancedConfig_Call) RunAndReturn(run func(context.Context, string, workload_eviction.AdvancedConfig, ...workload_eviction.RequestEditorFn) (*http.Response, error)) *MockClientInterface_EvictorAPIUpdateEvictorAdvancedConfig_Call {
	_c.Call.Return(run)
	return _c
}

// EvictorAPIUpdateEvictorAdvancedConfigWithBody provides a mock function with given fields: ctx, clusterId, contentType, body, reqEditors
func (_m *MockClientInterface) EvictorAPIUpdateEvictorAdvancedConfigWithBody(ctx context.Context, clusterId string, contentType string, body io.Reader, reqEditors ...workload_eviction.RequestEditorFn) (*http.Response, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, clusterId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for EvictorAPIUpdateEvictorAdvancedConfigWithBody")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...workload_eviction.RequestEditorFn) (*http.Response, error)); ok {
		return rf(ctx, clusterId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...workload_eviction.RequestEditorFn) *http.Response); ok {
		r0 = rf(ctx, clusterId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, ...workload_eviction.RequestEditorFn) error); ok {
		r1 = rf(ctx, clusterId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_EvictorAPIUpdateEvictorAdvancedConfigWithBody_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvictorAPIUpdateEvictorAdvancedConfigWithBody'
type MockClientInterface_EvictorAPIUpdateEvictorAdvancedConfigWithBody_Call struct {
	*mock.Call
}

// EvictorAPIUpdateEvictorAdvancedConfigWithBody is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterId string
//   - contentType string
//   - body io.Reader
//   - reqEditors ...workload_eviction.RequestEditorFn
func (_e *MockClientInterface_Expecter) EvictorAPIUpdateEvictorAdvancedConfigWithBody(ctx interface{}, clusterId interface{}, contentType interface{}, body interface{}, reqEditors ...interface{}) *MockClientInterface_EvictorAPIUpdateEvictorAdvancedConfigWithBody_Call {
	return &MockClientInterface_EvictorAPIUpdateEvictorAdvancedConfigWithBody_Call{Call: _e.mock.On("EvictorAPIUpdateEvictorAdvancedConfigWithBody",
		append([]interface{}{ctx, clusterId, contentType, body}, reqEditors...)...)}
}

func (_c *MockClientInterface_EvictorAPIUpdateEvictorAdvancedConfigWithBody_Call) Run(run func(ctx context.Context, clusterId string, contentType string, body io.Reader, reqEditors ...workload_eviction.RequestEditorFn)) *MockClientInterface_EvictorAPIUpdateEvictorAdvancedConfigWithBody_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]workload_eviction.RequestEditorFn, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(workload_eviction.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(io.Reader), variadicArgs...)
	})
	return _c
}

func (_c *MockClientInterface_EvictorAPIUpdateEvictorAdvancedConfigWithBody_Call) Return(_a0 *http.Response, _a1 error) *MockClientInterface_EvictorAPIUpdateEvictorAdvancedConfigWithBody_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_EvictorAPIUpdateEvictorAdvancedConfigWithBody_Call) RunAndReturn(run func(context.Context, string, string, io.Reader, ...workload_eviction.RequestEditorFn) (*http.Response, error)) *MockClientInterface_EvictorAPIUpdateEvictorAdvancedConfigWithBody_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientInterface creates a new instance of MockClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientInterface {
	mock := &MockClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
