package castai

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

	"github.com/castai/terraform-provider-castai/castai/sdk"
	"github.com/castai/terraform-provider-castai/castai/sdk/ai_optimizer"
)

const (
	fieldAIModelRegistryProviderType   = "provider_type"
	fieldAIModelRegistryS3             = "s3"
	fieldAIModelRegistryGCS            = "gcs"
	fieldAIModelRegistryBucket         = "bucket"
	fieldAIModelRegistryRegion         = "region"
	fieldAIModelRegistryPrefix         = "prefix"
	fieldAIModelRegistryCredentials    = "credentials"
	fieldAIModelRegistryUserName       = "user_name"
	fieldAIModelRegistryServiceAccount = "service_account"
	fieldAIModelRegistryStatus         = "status"
	fieldAIModelRegistryStatusReason   = "status_reason"
)

func resourceAIModelRegistry() *schema.Resource {
	return &schema.Resource{
		CreateContext: resourceAIModelRegistryCreate,
		ReadContext:   resourceAIModelRegistryRead,
		DeleteContext: resourceAIModelRegistryDelete,
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
		Schema: map[string]*schema.Schema{
			fieldAIModelRegistryProviderType: {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Default:     string(ai_optimizer.ProviderTypeS3),
				Description: "Provider type: S3 or GCS.",
				ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
					string(ai_optimizer.ProviderTypeS3),
					string(ai_optimizer.ProviderTypeGCS),
				}, false)),
			},
			fieldAIModelRegistryS3: {
				Type:          schema.TypeList,
				Optional:      true,
				ForceNew:      true,
				MaxItems:      1,
				Description:   "AWS S3 provider configuration. Required when provider_type is S3.",
				ConflictsWith: []string{fieldAIModelRegistryGCS},
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						fieldAIModelRegistryBucket: {
							Type:        schema.TypeString,
							Required:    true,
							Description: "S3 bucket name.",
						},
						fieldAIModelRegistryRegion: {
							Type:        schema.TypeString,
							Required:    true,
							Description: "AWS region of the S3 bucket.",
						},
						fieldAIModelRegistryPrefix: {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "Path prefix within the bucket.",
						},
						fieldAIModelRegistryUserName: {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "IAM user name created by onboarding.",
						},
					},
				},
			},
			fieldAIModelRegistryGCS: {
				Type:          schema.TypeList,
				Optional:      true,
				ForceNew:      true,
				MaxItems:      1,
				Description:   "Google Cloud Storage provider configuration. Required when provider_type is GCS.",
				ConflictsWith: []string{fieldAIModelRegistryS3},
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						fieldAIModelRegistryBucket: {
							Type:        schema.TypeString,
							Required:    true,
							Description: "GCS bucket name.",
						},
						fieldAIModelRegistryPrefix: {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "Path prefix within the bucket.",
						},
						fieldAIModelRegistryServiceAccount: {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Service account email generated by onboarding.",
						},
					},
				},
			},
			fieldAIModelRegistryCredentials: {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Sensitive:   true,
				Description: "JSON-encoded credentials for accessing the bucket.",
			},
			fieldAIModelRegistryStatus: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Registry status.",
			},
			fieldAIModelRegistryStatusReason: {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Reason for the current status.",
			},
		},
	}
}

func resourceAIModelRegistryCreate(ctx context.Context, d *schema.ResourceData, meta any) diag.Diagnostics {
	client := meta.(*ProviderConfig).aiOptimizerClient

	orgID, err := getDefaultOrganizationId(ctx, meta)
	if err != nil {
		return diag.FromErr(fmt.Errorf("fetching organization ID: %w", err))
	}

	providerType := ai_optimizer.ProviderType(d.Get(fieldAIModelRegistryProviderType).(string))
	credentials := d.Get(fieldAIModelRegistryCredentials).(string)

	body := ai_optimizer.ModelRegistry{
		Credentials: &credentials,
		Provider: ai_optimizer.Provider{
			Type: providerType,
		},
	}

	switch providerType {
	case ai_optimizer.ProviderTypeS3:
		s3List := d.Get(fieldAIModelRegistryS3).([]interface{})
		if len(s3List) == 0 {
			return diag.Errorf("s3 block is required when provider_type is S3")
		}
		s3 := s3List[0].(map[string]interface{})
		s3Config := ai_optimizer.ProviderS3Config{
			Bucket: s3[fieldAIModelRegistryBucket].(string),
			Region: s3[fieldAIModelRegistryRegion].(string),
		}
		if v, ok := s3[fieldAIModelRegistryPrefix].(string); ok && v != "" {
			s3Config.Prefix = &v
		}
		body.Provider.S3 = &s3Config
	case ai_optimizer.ProviderTypeGCS:
		gcsList := d.Get(fieldAIModelRegistryGCS).([]interface{})
		if len(gcsList) == 0 {
			return diag.Errorf("gcs block is required when provider_type is GCS")
		}
		gcs := gcsList[0].(map[string]interface{})
		gcsConfig := ai_optimizer.ProviderGcsConfig{
			Bucket: gcs[fieldAIModelRegistryBucket].(string),
		}
		if v, ok := gcs[fieldAIModelRegistryPrefix].(string); ok && v != "" {
			gcsConfig.Prefix = &v
		}
		body.Provider.Gcs = &gcsConfig
	default:
		return diag.Errorf("unsupported provider_type: %s", providerType)
	}

	tflog.Debug(ctx, "Creating AI model registry", map[string]any{"provider_type": string(providerType)})

	resp, err := client.ModelRegistriesAPICreateModelRegistryWithResponse(ctx, orgID, body)
	if err := sdk.CheckOKResponse(resp, err); err != nil {
		return diag.FromErr(fmt.Errorf("creating model registry: %w", err))
	}

	if resp.JSON200 == nil || resp.JSON200.Id == nil {
		return diag.FromErr(fmt.Errorf("unexpected empty response from create model registry"))
	}

	d.SetId(*resp.JSON200.Id)

	return resourceAIModelRegistryRead(ctx, d, meta)
}

func resourceAIModelRegistryRead(ctx context.Context, d *schema.ResourceData, meta any) diag.Diagnostics {
	client := meta.(*ProviderConfig).aiOptimizerClient

	orgID, err := getDefaultOrganizationId(ctx, meta)
	if err != nil {
		return diag.FromErr(fmt.Errorf("fetching organization ID: %w", err))
	}

	resp, err := client.ModelRegistriesAPIGetModelRegistryWithResponse(ctx, orgID, d.Id())
	if err != nil {
		return diag.FromErr(err)
	}
	if !d.IsNewResource() && resp.StatusCode() == http.StatusNotFound {
		tflog.Warn(ctx, "AI model registry not found, removing from state", map[string]any{"id": d.Id()})
		d.SetId("")
		return nil
	}
	if err := sdk.CheckOKResponse(resp, nil); err != nil {
		return diag.FromErr(fmt.Errorf("reading model registry: %w", err))
	}

	reg := resp.JSON200
	if reg == nil {
		return diag.FromErr(fmt.Errorf("unexpected empty response reading model registry %q", d.Id()))
	}

	if err := d.Set(fieldAIModelRegistryProviderType, string(reg.Provider.Type)); err != nil {
		return diag.FromErr(fmt.Errorf("setting provider_type: %w", err))
	}

	if reg.Provider.S3 != nil {
		s3 := map[string]interface{}{
			fieldAIModelRegistryBucket: reg.Provider.S3.Bucket,
			fieldAIModelRegistryRegion: reg.Provider.S3.Region,
		}
		if reg.Provider.S3.Prefix != nil {
			s3[fieldAIModelRegistryPrefix] = *reg.Provider.S3.Prefix
		}
		if reg.Provider.S3.UserName != nil {
			s3[fieldAIModelRegistryUserName] = *reg.Provider.S3.UserName
		}
		if err := d.Set(fieldAIModelRegistryS3, []interface{}{s3}); err != nil {
			return diag.FromErr(fmt.Errorf("setting s3: %w", err))
		}
	}

	if reg.Provider.Gcs != nil {
		gcs := map[string]interface{}{
			fieldAIModelRegistryBucket: reg.Provider.Gcs.Bucket,
		}
		if reg.Provider.Gcs.Prefix != nil {
			gcs[fieldAIModelRegistryPrefix] = *reg.Provider.Gcs.Prefix
		}
		if reg.Provider.Gcs.ServiceAccount != nil {
			gcs[fieldAIModelRegistryServiceAccount] = *reg.Provider.Gcs.ServiceAccount
		}
		if err := d.Set(fieldAIModelRegistryGCS, []interface{}{gcs}); err != nil {
			return diag.FromErr(fmt.Errorf("setting gcs: %w", err))
		}
	}

	if reg.Status != nil {
		if err := d.Set(fieldAIModelRegistryStatus, string(*reg.Status)); err != nil {
			return diag.FromErr(fmt.Errorf("setting status: %w", err))
		}
	}
	if reg.StatusReason != nil {
		if err := d.Set(fieldAIModelRegistryStatusReason, *reg.StatusReason); err != nil {
			return diag.FromErr(fmt.Errorf("setting status_reason: %w", err))
		}
	}

	return nil
}

func resourceAIModelRegistryDelete(ctx context.Context, d *schema.ResourceData, meta any) diag.Diagnostics {
	client := meta.(*ProviderConfig).aiOptimizerClient

	orgID, err := getDefaultOrganizationId(ctx, meta)
	if err != nil {
		return diag.FromErr(fmt.Errorf("fetching organization ID: %w", err))
	}

	tflog.Debug(ctx, "Deleting AI model registry", map[string]any{"id": d.Id()})

	resp, err := client.ModelRegistriesAPIDeleteModelRegistryWithResponse(ctx, orgID, d.Id())
	if err := sdk.CheckOKResponse(resp, err); err != nil {
		return diag.FromErr(fmt.Errorf("deleting model registry: %w", err))
	}

	return nil
}
