// Package patching_engine provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package patching_engine

import (
	"encoding/json"
	"fmt"
	"time"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for DistributionGroupConfigSpotType.
const (
	DistributionGroupConfigSpotTypeOPTIONALSPOT        DistributionGroupConfigSpotType = "OPTIONAL_SPOT"
	DistributionGroupConfigSpotTypePREFERREDSPOT       DistributionGroupConfigSpotType = "PREFERRED_SPOT"
	DistributionGroupConfigSpotTypeSPOTTYPEUNSPECIFIED DistributionGroupConfigSpotType = "SPOT_TYPE_UNSPECIFIED"
	DistributionGroupConfigSpotTypeUSEONLYSPOT         DistributionGroupConfigSpotType = "USE_ONLY_SPOT"
)

// Defines values for ObjectFilterExcludeLabelsOperator.
const (
	ObjectFilterExcludeLabelsOperatorAND                       ObjectFilterExcludeLabelsOperator = "AND"
	ObjectFilterExcludeLabelsOperatorFILTEROPERATORUNSPECIFIED ObjectFilterExcludeLabelsOperator = "FILTER_OPERATOR_UNSPECIFIED"
	ObjectFilterExcludeLabelsOperatorOR                        ObjectFilterExcludeLabelsOperator = "OR"
)

// Defines values for ObjectFilterLabelsOperator.
const (
	ObjectFilterLabelsOperatorAND                       ObjectFilterLabelsOperator = "AND"
	ObjectFilterLabelsOperatorFILTEROPERATORUNSPECIFIED ObjectFilterLabelsOperator = "FILTER_OPERATOR_UNSPECIFIED"
	ObjectFilterLabelsOperatorOR                        ObjectFilterLabelsOperator = "OR"
)

// Defines values for ObjectFilterV2LabelsFilterOperator.
const (
	AND                       ObjectFilterV2LabelsFilterOperator = "AND"
	FILTEROPERATORUNSPECIFIED ObjectFilterV2LabelsFilterOperator = "FILTER_OPERATOR_UNSPECIFIED"
	OR                        ObjectFilterV2LabelsFilterOperator = "OR"
)

// Defines values for ObjectFilterV2MatcherType.
const (
	EXACT           ObjectFilterV2MatcherType = "EXACT"
	REGEX           ObjectFilterV2MatcherType = "REGEX"
	TYPEUNSPECIFIED ObjectFilterV2MatcherType = "TYPE_UNSPECIFIED"
)

// Defines values for PodMutationSource.
const (
	API               PodMutationSource = "API"
	CUSTOMRESOURCE    PodMutationSource = "CUSTOM_RESOURCE"
	SOURCEUNSPECIFIED PodMutationSource = "SOURCE_UNSPECIFIED"
)

// Defines values for PodMutationSpotType.
const (
	PodMutationSpotTypeOPTIONALSPOT        PodMutationSpotType = "OPTIONAL_SPOT"
	PodMutationSpotTypePREFERREDSPOT       PodMutationSpotType = "PREFERRED_SPOT"
	PodMutationSpotTypeSPOTTYPEUNSPECIFIED PodMutationSpotType = "SPOT_TYPE_UNSPECIFIED"
	PodMutationSpotTypeUSEONLYSPOT         PodMutationSpotType = "USE_ONLY_SPOT"
)

// Defines values for PodMutatorStatusStatus.
const (
	DISABLED          PodMutatorStatusStatus = "DISABLED"
	INVALID           PodMutatorStatusStatus = "INVALID"
	RUNNING           PodMutatorStatusStatus = "RUNNING"
	STATUSUNSPECIFIED PodMutatorStatusStatus = "STATUS_UNSPECIFIED"
)

// Defines values for PodMutationsAPIListWorkloadPreviewsParamsWorkloadType.
const (
	AFFECTED                PodMutationsAPIListWorkloadPreviewsParamsWorkloadType = "AFFECTED"
	UNAFFECTED              PodMutationsAPIListWorkloadPreviewsParamsWorkloadType = "UNAFFECTED"
	WORKLOADTYPEUNSPECIFIED PodMutationsAPIListWorkloadPreviewsParamsWorkloadType = "WORKLOAD_TYPE_UNSPECIFIED"
)

// Defines values for PodMutationsAPIListWorkloadPreviewsParamsSortOrder.
const (
	ASC  PodMutationsAPIListWorkloadPreviewsParamsSortOrder = "ASC"
	Asc  PodMutationsAPIListWorkloadPreviewsParamsSortOrder = "asc"
	DESC PodMutationsAPIListWorkloadPreviewsParamsSortOrder = "DESC"
	Desc PodMutationsAPIListWorkloadPreviewsParamsSortOrder = "desc"
)

// Affinity Affinity represents the affinity settings for the pod mutation.
type Affinity struct {
	// NodeAffinity Node affinity settings.
	NodeAffinity *NodeAffinity `json:"nodeAffinity,omitempty"`
}

// CloudMetadata CloudMetadata contains details about where an error came from.
type CloudMetadata struct {
	// InstanceType Instance type (optional) that caused an error.
	InstanceType *string `json:"instanceType,omitempty"`

	// Provider Cloud provider that returned an error.
	Provider *string `json:"provider,omitempty"`

	// Region Region related to an error.
	Region *string `json:"region,omitempty"`

	// Zone Zone details related to an error.
	Zone *Zone `json:"zone,omitempty"`
}

// DistributionGroup DistributionGroup represents a group of pods that should receive specific configurations
//
//	based on a percentage distribution.
type DistributionGroup struct {
	// Config Configuration to apply to pods in this distribution group.
	Config *DistributionGroupConfig `json:"config,omitempty"`

	// Name Unique name for this distribution group within the pod mutation.
	Name *string `json:"name,omitempty"`

	// Percentage Percentage of pods (0-100) that should receive this configuration group.
	//  The sum of all distribution group percentages within a pod mutation must not exceed 100.
	Percentage *int32 `json:"percentage,omitempty"`
}

// DistributionGroupConfig DistributionGroupConfig defines the specific configurations that can be applied
//
//	to pods within a distribution group.
type DistributionGroupConfig struct {
	// Affinity Affinity to apply to pods in this distribution group.
	Affinity *Affinity `json:"affinity,omitempty"`

	// Annotations Annotations to add to pods in this distribution group.
	Annotations *map[string]string `json:"annotations,omitempty"`

	// Labels Labels to add to pods in this distribution group.
	Labels *map[string]string `json:"labels,omitempty"`

	// NodeSelector Node selector to apply to pods in this distribution group.
	NodeSelector *PatchOptions `json:"nodeSelector,omitempty"`

	// NodeTemplatesToConsolidate Node template names to consolidate for pods in this distribution group.
	NodeTemplatesToConsolidate *[]string `json:"nodeTemplatesToConsolidate,omitempty"`

	// Patch JSON patches to apply to pods in this distribution group.
	//  These patches are applied after all other configurations in the group.
	Patch *[]map[string]interface{} `json:"patch,omitempty"`

	// SpotType SpotType specifies the type of spot instance to use for pods in this distribution group.
	SpotType *DistributionGroupConfigSpotType `json:"spotType,omitempty"`

	// Tolerations Tolerations to apply to pods in this distribution group.
	Tolerations *[]Toleration `json:"tolerations,omitempty"`
}

// DistributionGroupConfigSpotType SpotType specifies the type of spot instance to use for pods in this distribution group.
type DistributionGroupConfigSpotType string

// ErrorResponse ErrorResponse is intended to be returned to external caller (e.g. REST).
type ErrorResponse struct {
	// FieldViolations Field violations.
	FieldViolations *[]FieldViolation `json:"fieldViolations,omitempty"`

	// Message Error message.
	Message *string `json:"message,omitempty"`

	// Origin Origin contains details about error where it came from (like Cloud provider, region, etc.).
	Origin *CloudMetadata `json:"origin,omitempty"`

	// Reason Reason that categorizes an error.
	Reason *string `json:"reason,omitempty"`

	// Retryable Whether error is retryable.
	Retryable *bool `json:"retryable,omitempty"`
}

// FieldViolation FieldViolation contains validation result for single field.
type FieldViolation struct {
	// Description Description of the violation.
	Description *string `json:"description,omitempty"`

	// Field Field name.
	Field *string `json:"field,omitempty"`
}

// GetPodMutatorInstallCmdResponse GetPodMutatorInstallCmdResponse represents the response to get the command to install the pod mutator.
type GetPodMutatorInstallCmdResponse struct {
	// Cmd The command to install the pod mutator
	Cmd *string `json:"cmd,omitempty"`
}

// GetPodMutatorInstallScriptResponse GetPodMutatorInstallScriptResponse represents the response to get the script to install the pod mutator.
type GetPodMutatorInstallScriptResponse struct {
	// Script The script to install the pod mutator
	Script string `json:"script"`
}

// GoogleProtobufAny Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
type GoogleProtobufAny struct {
	// Type The type of the serialized message.
	Type                 *string                `json:"@type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ListPodMutationsResponse ListPodMutationsResponse represents a response to list pod mutations.
type ListPodMutationsResponse struct {
	// Items The list of pod mutations.
	Items *[]PodMutation `json:"items,omitempty"`

	// NextPageCursor The pagination cursor to retrieve the next page of pod mutations.
	NextPageCursor *string `json:"nextPageCursor,omitempty"`
}

// ListWorkloadPreviewsResponse ListWorkloadPreviewsResponse contains paginated workload preview results.
type ListWorkloadPreviewsResponse struct {
	// Items Workloads.
	Items *[]Workload `json:"items,omitempty"`

	// NextPageCursor The pagination cursor to retrieve the next page.
	NextPageCursor *string `json:"nextPageCursor,omitempty"`
}

// LongRunningOperation Operation represents the result of an asynchronous operation.
type LongRunningOperation struct {
	// Done Whether the operation is completed.
	Done *bool `json:"done,omitempty"`

	// Error Error returned of the operation.
	Error *ErrorResponse `json:"error,omitempty"`

	// Id ID of the operation.
	Id *string `json:"id,omitempty"`

	// ResourceId Resource ID returned of the operation.
	ResourceId *string `json:"resourceId,omitempty"`
}

// MatchedMutation MatchedMutation represents a mutation which is matching a workload.
type MatchedMutation struct {
	// Name The Name of the pod mutation.
	Name *string `json:"name,omitempty"`

	// Rank The rank of the pod mutation (lower number indicates a more specific match).
	Rank *int32 `json:"rank,omitempty"`
}

// MatchedWorkload MatchedWorkload represents a workload that matches the requested filter.
type MatchedWorkload struct {
	// Kind The workload kind.
	Kind *string `json:"kind,omitempty"`

	// MatchedMutations All mutations that match the workload.
	MatchedMutations *[]MatchedMutation `json:"matchedMutations,omitempty"`

	// Name The workload name.
	Name *string `json:"name,omitempty"`

	// Namespace The workload namespace.
	Namespace *string `json:"namespace,omitempty"`

	// PodCount The number of pods in the workload.
	PodCount *int32 `json:"podCount,omitempty"`

	// Targeted Indicates whether the mutation for the requested filters is the one selected for a given workload (has the highest ranking).
	Targeted *bool `json:"targeted,omitempty"`
}

// NodeAffinity NodeAffinity represents the node affinity settings for the pod mutation.
type NodeAffinity struct {
	// PreferredDuringSchedulingIgnoredDuringExecution Node affinity terms that are preferred during scheduling but ignored during execution.
	PreferredDuringSchedulingIgnoredDuringExecution *[]NodeAffinityWeightedNodeAffinityTerm `json:"preferredDuringSchedulingIgnoredDuringExecution,omitempty"`
}

// NodeAffinityWeightedNodeAffinityTerm Node affinity terms that are preferred during scheduling but ignored during execution.
type NodeAffinityWeightedNodeAffinityTerm struct {
	// Preference Node affinity term.
	Preference *NodeSelectorTerm `json:"preference,omitempty"`

	// Weight Weight of the node affinity term.
	Weight *int32 `json:"weight,omitempty"`
}

// NodeSelectorRequirement NodeSelectorRequirement represents a node selector requirement.
type NodeSelectorRequirement struct {
	// Key Key of the node selector requirement.
	Key *string `json:"key,omitempty"`

	// Operator Operator of the node selector requirement.
	Operator *string `json:"operator,omitempty"`

	// Values Values of the node selector requirement.
	Values *[]string `json:"values,omitempty"`
}

// NodeSelectorTerm NodeSelectorTerm represents a node selector term.
type NodeSelectorTerm struct {
	// MatchExpressions Node selector requirements.
	MatchExpressions *[]NodeSelectorRequirement `json:"matchExpressions,omitempty"`
}

// ObjectFilter ObjectFilter represents a filter for Kubernetes objects.
type ObjectFilter struct {
	// ExcludeKinds Object kinds that should be excluded from applying mutation. Empty means none kinds.
	ExcludeKinds *[]string `json:"excludeKinds,omitempty"`

	// ExcludeLabelsFilter Labels filter for the objects that should be excluded from applying mutation.
	ExcludeLabelsFilter *[]ObjectFilterLabelValue `json:"excludeLabelsFilter,omitempty"`

	// ExcludeLabelsOperator Filter operator for exclude labels filter
	ExcludeLabelsOperator *ObjectFilterExcludeLabelsOperator `json:"excludeLabelsOperator,omitempty"`

	// ExcludeNames Names of the objects that should be excluded from applying mutation. Empty means none objects.
	ExcludeNames *[]string `json:"excludeNames,omitempty"`

	// ExcludeNamespaces Namespaces of the objects that should be excluded from applying mutation. Empty means none objects.
	ExcludeNamespaces *[]string `json:"excludeNamespaces,omitempty"`

	// Kinds Object kinds that the pod mutation should apply to. Empty means all kinds.
	Kinds *[]string `json:"kinds,omitempty"`

	// LabelsFilter Labels filter that the pod mutation should apply to.
	LabelsFilter *[]ObjectFilterLabelValue `json:"labelsFilter,omitempty"`

	// LabelsOperator Filter operator for labels filter
	LabelsOperator *ObjectFilterLabelsOperator `json:"labelsOperator,omitempty"`

	// Names Names of the objects that the pod mutation should apply to. Empty means all objects.
	Names *[]string `json:"names,omitempty"`

	// Namespaces Namespaces of the objects that the pod mutation should apply to. Empty means all namespaces.
	Namespaces *[]string `json:"namespaces,omitempty"`
}

// ObjectFilterExcludeLabelsOperator Filter operator for exclude labels filter
type ObjectFilterExcludeLabelsOperator string

// ObjectFilterLabelsOperator Filter operator for labels filter
type ObjectFilterLabelsOperator string

// ObjectFilterV2 ObjectFilterV2 represents an advanced filter for Kubernetes objects with support for exact and regex matching.
type ObjectFilterV2 struct {
	// ExcludeKinds Kinds of the objects that should be excluded from applying mutation. Empty means none kinds.
	ExcludeKinds *[]ObjectFilterV2Matcher `json:"excludeKinds,omitempty"`

	// ExcludeLabels Labels filter for the objects that should be excluded from applying mutation.
	ExcludeLabels *ObjectFilterV2LabelsFilter `json:"excludeLabels,omitempty"`

	// ExcludeNames Names of the objects that should be excluded from applying mutation. Empty means none objects.
	ExcludeNames *[]ObjectFilterV2Matcher `json:"excludeNames,omitempty"`

	// ExcludeNamespaces Namespaces of the objects that should be excluded from applying mutation. Empty means none objects.
	ExcludeNamespaces *[]ObjectFilterV2Matcher `json:"excludeNamespaces,omitempty"`

	// Kinds Kinds of the objects that the pod mutation should apply to. Empty means all kinds.
	Kinds *[]ObjectFilterV2Matcher `json:"kinds,omitempty"`

	// Labels Labels filter that the pod mutation should apply to.
	Labels *ObjectFilterV2LabelsFilter `json:"labels,omitempty"`

	// Names Names of the objects that the pod mutation should apply to. Empty means all objects.
	Names *[]ObjectFilterV2Matcher `json:"names,omitempty"`

	// Namespaces Namespaces of the objects that the pod mutation should apply to. Empty means all namespaces.
	Namespaces *[]ObjectFilterV2Matcher `json:"namespaces,omitempty"`
}

// ObjectFilterV2LabelMatcher LabelMatcher defines a key-value pair for label matching.
type ObjectFilterV2LabelMatcher struct {
	// Key Key matcher.
	Key *ObjectFilterV2Matcher `json:"key,omitempty"`

	// Value Value matcher.
	Value *ObjectFilterV2Matcher `json:"value,omitempty"`
}

// ObjectFilterV2LabelsFilter LabelsFilter defines a set of label matchers combined with a logical operator.
type ObjectFilterV2LabelsFilter struct {
	// Matchers List of label matchers.
	Matchers *[]ObjectFilterV2LabelMatcher `json:"matchers,omitempty"`

	// Operator Operator to combine the label matchers.
	Operator *ObjectFilterV2LabelsFilterOperator `json:"operator,omitempty"`
}

// ObjectFilterV2LabelsFilterOperator Operator to combine the label matchers.
type ObjectFilterV2LabelsFilterOperator string

// ObjectFilterV2Matcher Matcher defines a matching rule for filtering.
type ObjectFilterV2Matcher struct {
	// Type Type of the matcher.
	Type *ObjectFilterV2MatcherType `json:"type,omitempty"`

	// Value Value to match against.
	Value *string `json:"value,omitempty"`
}

// ObjectFilterV2MatcherType Type of the matcher.
type ObjectFilterV2MatcherType string

// ObjectFilterLabelValue LabelValue represents a label and its value.
type ObjectFilterLabelValue struct {
	// Label Label key.
	Label *string `json:"label,omitempty"`

	// Value Label value.
	Value *string `json:"value,omitempty"`
}

// PatchOptions PatchOptions represents a set of key-value pairs to add or remove.
type PatchOptions struct {
	// Add Key-value pairs to add.
	Add *map[string]string `json:"add,omitempty"`

	// Remove Key-value pairs to remove.
	Remove *map[string]string `json:"remove,omitempty"`
}

// PodMutation PodMutation represents a mutation that can be applied to pods in a cluster.
type PodMutation struct {
	// Affinity Affinity to apply to the pods.
	Affinity *Affinity `json:"affinity,omitempty"`

	// Annotations Annotations to add to the pods.
	Annotations *map[string]string `json:"annotations,omitempty"`

	// ClusterId The cluster ID.
	ClusterId *string `json:"clusterId,omitempty"`

	// CreateTime The timestamp when the pod mutation was created
	CreateTime *time.Time `json:"createTime,omitempty"`

	// DistributionGroups Distribution groups allow percentage-based distribution of configurations across pods.
	//  Each group defines a percentage of pods that should receive specific configurations.
	//  This enables scenarios like "70% of pods get label A, 30% get label B" or
	//  "20% consolidate to node template A, 80% to template B".
	//
	//  Validation rules (enforced by service logic):
	//  - Sum of all distribution group percentages must not exceed 100
	//  - Distribution group names must be unique within this pod mutation
	DistributionGroups *[]DistributionGroup `json:"distributionGroups,omitempty"`

	// Enabled Indicates whether the pod mutation is enabled.
	Enabled *bool `json:"enabled,omitempty"`

	// Id The ID of the pod mutation.
	Id *string `json:"id,omitempty"`

	// Labels Labels to add to the pods.
	Labels *map[string]string `json:"labels,omitempty"`

	// MutatedPodsCount The number of pods that have been mutated by this pod mutation.
	MutatedPodsCount *int32 `json:"mutatedPodsCount,omitempty"`

	// Name The name of the pod mutation.
	Name *string `json:"name,omitempty"`

	// NodeSelector Node selector to apply to the pods.
	NodeSelector *PatchOptions `json:"nodeSelector,omitempty"`

	// NodeTemplatesToConsolidate Node template names to consolidate
	NodeTemplatesToConsolidate *[]string `json:"nodeTemplatesToConsolidate,omitempty"`

	// ObjectFilter Deprecated: Use object_filter_v2 instead.
	//  Object filter used to filter the Kubernetes objects that the pod mutation should apply to.
	// Deprecated:
	ObjectFilter *ObjectFilter `json:"objectFilter,omitempty"`

	// ObjectFilterV2 Object filter used to filter the Kubernetes objects that the pod mutation should apply to.
	ObjectFilterV2 *ObjectFilterV2 `json:"objectFilterV2,omitempty"`

	// OrganizationId The organization ID.
	OrganizationId *string `json:"organizationId,omitempty"`

	// Patch Optional patching field that allows mutation of pod definitions using the standard
	//  JSON patch mechanism. All preceding mutations have a priority, and the patch is
	//  applied at the end. Setting this field does not guarantee that it won't override
	//  mutations set in previous fields. For example, if a label is added via the labels
	//  field and then removed by the patch, the label will be removed.
	//  For more detailed explanation read JSON patching section in kubernetes documentation:
	//  https://kubernetes.io/docs/reference/kubectl/generated/kubectl_patch/
	Patch *[]map[string]interface{} `json:"patch,omitempty"`

	// RestartMatchingWorkloads Restart matching workloads when the pod mutation is applied.
	RestartMatchingWorkloads *bool `json:"restartMatchingWorkloads,omitempty"`

	// Source The source of the pod mutation.
	Source *PodMutationSource `json:"source,omitempty"`

	// SpotDistributionPercentage The percentage of pods (0-100) that receive spot scheduling constraints.
	//  The specific spot scheduling constraints depend on the selected SpotType.
	//  At least the remaining percentage will be scheduled on on-demand instances.
	//  This field applies only if SpotType is specified.
	SpotDistributionPercentage *int32 `json:"spotDistributionPercentage,omitempty"`

	// SpotType The type of spot instance to use.
	SpotType *PodMutationSpotType `json:"spotType,omitempty"`

	// Tolerations Tolerations to apply to the pods.
	Tolerations *[]Toleration `json:"tolerations,omitempty"`

	// UpdateTime The timestamp when the pod mutation was last updated
	UpdateTime *time.Time `json:"updateTime,omitempty"`
}

// PodMutationSource The source of the pod mutation.
type PodMutationSource string

// PodMutationSpotType The type of spot instance to use.
type PodMutationSpotType string

// PodMutatorStatus PodMutatorStatus represents the status of the pod mutator in the cluster.
type PodMutatorStatus struct {
	// Status Status of the pod mutator
	Status *PodMutatorStatusStatus `json:"status,omitempty"`
}

// PodMutatorStatusStatus Status of the pod mutator
type PodMutatorStatusStatus string

// PreviewMatchedWorkloadsRequest PreviewMatchedWorkloadsRequest represents a request to simulate which workloads would be matched for a specific pod mutation filters.
type PreviewMatchedWorkloadsRequest struct {
	// ClusterId The cluster ID.
	ClusterId string `json:"clusterId"`

	// Name The name of the pod mutation.
	Name *string `json:"name,omitempty"`

	// ObjectFilter Deprecated: Use object_filter_v2 instead.
	//  Object filter to match the Kubernetes objects.
	// Deprecated:
	ObjectFilter *ObjectFilter `json:"objectFilter,omitempty"`

	// ObjectFilterV2 Object filter to match the Kubernetes objects.
	ObjectFilterV2 *ObjectFilterV2 `json:"objectFilterV2,omitempty"`

	// OrganizationId The organization ID.
	OrganizationId string `json:"organizationId"`
}

// PreviewMatchedWorkloadsResponse PreviewMatchedWorkloadsResponse represents the response containing the list of workloads that are matched by the specified pod mutation filters.
type PreviewMatchedWorkloadsResponse struct {
	// MatchedWorkloads The matched workloads.
	MatchedWorkloads *[]MatchedWorkload `json:"matchedWorkloads,omitempty"`

	// UnmatchedWorkloads The unmatched workloads.
	UnmatchedWorkloads *[]UnmatchedWorkload `json:"unmatchedWorkloads,omitempty"`
}

// Status The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors).
type Status struct {
	// Code The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
	Code *int32 `json:"code,omitempty"`

	// Details A list of messages that carry the error details.  There is a common set of message types for APIs to use.
	Details *[]GoogleProtobufAny `json:"details,omitempty"`

	// Message A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
	Message *string `json:"message,omitempty"`
}

// Toleration Toleration represents a toleration for the pod mutation.
type Toleration struct {
	// Effect Effect of the toleration.
	Effect *string `json:"effect,omitempty"`

	// Key Key of the toleration.
	Key *string `json:"key,omitempty"`

	// Operator Operator of the toleration.
	Operator *string `json:"operator,omitempty"`

	// TolerationSeconds Optional toleration seconds.
	TolerationSeconds *string `json:"tolerationSeconds,omitempty"`

	// Value Value of the toleration.
	Value *string `json:"value,omitempty"`
}

// UnmatchedWorkload UnmatchedWorkload represents a workload that does not match the requested filter.
type UnmatchedWorkload struct {
	// Kind The workload kind.
	Kind *string `json:"kind,omitempty"`

	// Name The workload name.
	Name *string `json:"name,omitempty"`

	// Namespace The workload namespace.
	Namespace *string `json:"namespace,omitempty"`

	// PodCount The number of pods in the workload.
	PodCount *int32 `json:"podCount,omitempty"`
}

// Workload Workload represents a Kubernetes workload resource.
type Workload struct {
	// Kind The workload kind.
	Kind *string `json:"kind,omitempty"`

	// Name The workload name.
	Name *string `json:"name,omitempty"`

	// Namespace The workload namespace.
	Namespace *string `json:"namespace,omitempty"`

	// PodCount The number of pods in the workload.
	PodCount *int32 `json:"podCount,omitempty"`
}

// WorkloadPreviewParameters WorkloadPreviewParameters contains parameters for generating a workload preview.
type WorkloadPreviewParameters struct {
	// ClusterId Cluster ID.
	ClusterId *string `json:"clusterId,omitempty"`

	// Name The name of the pod mutation to preview.
	Name string `json:"name"`

	// ObjectFilter Deprecated: Use object_filter_v2 instead.
	//  Object filter used to filter the Kubernetes objects that the pod mutation should apply to.
	// Deprecated:
	ObjectFilter *ObjectFilter `json:"objectFilter,omitempty"`

	// ObjectFilterV2 Object filter used to filter the Kubernetes objects that the pod mutation should apply to.
	ObjectFilterV2 *ObjectFilterV2 `json:"objectFilterV2,omitempty"`

	// OrganizationId Organization ID.
	OrganizationId *string `json:"organizationId,omitempty"`
}

// Zone Zone contains details required to identify error related zone.
type Zone struct {
	// Id Zone ID related to an error.
	Id *string `json:"id,omitempty"`

	// Name Zone name related to an error.
	Name *string `json:"name,omitempty"`
}

// PodMutationsAPIListPodMutationsParams defines parameters for PodMutationsAPIListPodMutations.
type PodMutationsAPIListPodMutationsParams struct {
	// PageLimit Defines the number of items that should be returned
	PageLimit *string `form:"page.limit,omitempty" json:"page.limit,omitempty"`

	// PageCursor Cursor that defines token indicating where to start the next page.
	//  Empty value indicates to start from beginning of the dataset.
	PageCursor *string `form:"page.cursor,omitempty" json:"page.cursor,omitempty"`

	// Enabled If set, returns only enabled/disabled pod mutations
	Enabled *bool `form:"enabled,omitempty" json:"enabled,omitempty"`

	// MaterializePatch Returns full view of the pod mutation to apply
	MaterializePatch *bool `form:"materializePatch,omitempty" json:"materializePatch,omitempty"`
}

// PodMutationsAPIListWorkloadPreviewsParams defines parameters for PodMutationsAPIListWorkloadPreviews.
type PodMutationsAPIListWorkloadPreviewsParams struct {
	// OperationId Operation ID
	OperationId *string `form:"operationId,omitempty" json:"operationId,omitempty"`

	// WorkloadType Workload type to retrieve (affected or unaffected).
	WorkloadType *PodMutationsAPIListWorkloadPreviewsParamsWorkloadType `form:"workloadType,omitempty" json:"workloadType,omitempty"`

	// PageLimit Defines the number of items that should be returned
	PageLimit *string `form:"page.limit,omitempty" json:"page.limit,omitempty"`

	// PageCursor Cursor that defines token indicating where to start the next page.
	//  Empty value indicates to start from beginning of the dataset.
	PageCursor *string `form:"page.cursor,omitempty" json:"page.cursor,omitempty"`

	// SortField The field name to order by. Nested fields can be specified by using a dot (e.g. user.name).
	SortField *string `form:"sort.field,omitempty" json:"sort.field,omitempty"`

	// SortOrder The order of returned items. Default is ASC.
	SortOrder *PodMutationsAPIListWorkloadPreviewsParamsSortOrder `form:"sort.order,omitempty" json:"sort.order,omitempty"`

	// FilterNames Filter by workload names. Empty means no filter.
	FilterNames *[]string `form:"filter.names,omitempty" json:"filter.names,omitempty"`

	// FilterKinds Filter by workload kinds. Empty means no filter.
	FilterKinds *[]string `form:"filter.kinds,omitempty" json:"filter.kinds,omitempty"`

	// FilterNamespaces Filter by workload namespaces. Empty means no filter.
	FilterNamespaces *[]string `form:"filter.namespaces,omitempty" json:"filter.namespaces,omitempty"`
}

// PodMutationsAPIListWorkloadPreviewsParamsWorkloadType defines parameters for PodMutationsAPIListWorkloadPreviews.
type PodMutationsAPIListWorkloadPreviewsParamsWorkloadType string

// PodMutationsAPIListWorkloadPreviewsParamsSortOrder defines parameters for PodMutationsAPIListWorkloadPreviews.
type PodMutationsAPIListWorkloadPreviewsParamsSortOrder string

// PodMutationsAPICreatePodMutationJSONRequestBody defines body for PodMutationsAPICreatePodMutation for application/json ContentType.
type PodMutationsAPICreatePodMutationJSONRequestBody = PodMutation

// PodMutationsAPIUpdatePodMutationJSONRequestBody defines body for PodMutationsAPIUpdatePodMutation for application/json ContentType.
type PodMutationsAPIUpdatePodMutationJSONRequestBody = PodMutation

// PodMutationsAPIPreviewMatchedWorkloadsJSONRequestBody defines body for PodMutationsAPIPreviewMatchedWorkloads for application/json ContentType.
type PodMutationsAPIPreviewMatchedWorkloadsJSONRequestBody = PreviewMatchedWorkloadsRequest

// PodMutationsAPIGenerateWorkloadPreviewsJSONRequestBody defines body for PodMutationsAPIGenerateWorkloadPreviews for application/json ContentType.
type PodMutationsAPIGenerateWorkloadPreviewsJSONRequestBody = WorkloadPreviewParameters

// Getter for additional properties for GoogleProtobufAny. Returns the specified
// element and whether it was found
func (a GoogleProtobufAny) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for GoogleProtobufAny
func (a *GoogleProtobufAny) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for GoogleProtobufAny to handle AdditionalProperties
func (a *GoogleProtobufAny) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["@type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading '@type': %w", err)
		}
		delete(object, "@type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for GoogleProtobufAny to handle AdditionalProperties
func (a GoogleProtobufAny) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Type != nil {
		object["@type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '@type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
