// Package patching_engine provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package patching_engine

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PodMutationsAPIListPodMutations request
	PodMutationsAPIListPodMutations(ctx context.Context, organizationId string, clusterId string, params *PodMutationsAPIListPodMutationsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PodMutationsAPICreatePodMutationWithBody request with any body
	PodMutationsAPICreatePodMutationWithBody(ctx context.Context, organizationId string, clusterId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PodMutationsAPICreatePodMutation(ctx context.Context, organizationId string, clusterId string, body PodMutationsAPICreatePodMutationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PodMutationsAPIDeletePodMutation request
	PodMutationsAPIDeletePodMutation(ctx context.Context, organizationId string, clusterId string, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PodMutationsAPIGetPodMutation request
	PodMutationsAPIGetPodMutation(ctx context.Context, organizationId string, clusterId string, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PodMutationsAPIUpdatePodMutationWithBody request with any body
	PodMutationsAPIUpdatePodMutationWithBody(ctx context.Context, organizationId string, clusterId string, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PodMutationsAPIUpdatePodMutation(ctx context.Context, organizationId string, clusterId string, id string, body PodMutationsAPIUpdatePodMutationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PodMutationsAPIPreviewMatchedWorkloadsWithBody request with any body
	PodMutationsAPIPreviewMatchedWorkloadsWithBody(ctx context.Context, organizationId string, clusterId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PodMutationsAPIPreviewMatchedWorkloads(ctx context.Context, organizationId string, clusterId string, body PodMutationsAPIPreviewMatchedWorkloadsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PodMutationsAPIGetPodMutatorStatus request
	PodMutationsAPIGetPodMutatorStatus(ctx context.Context, organizationId string, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PodMutationsAPIListWorkloadPreviews request
	PodMutationsAPIListWorkloadPreviews(ctx context.Context, organizationId string, clusterId string, params *PodMutationsAPIListWorkloadPreviewsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PodMutationsAPIGenerateWorkloadPreviewsWithBody request with any body
	PodMutationsAPIGenerateWorkloadPreviewsWithBody(ctx context.Context, organizationId string, clusterId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PodMutationsAPIGenerateWorkloadPreviews(ctx context.Context, organizationId string, clusterId string, body PodMutationsAPIGenerateWorkloadPreviewsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PodMutationsAPIGetPodMutatorInstallCmd request
	PodMutationsAPIGetPodMutatorInstallCmd(ctx context.Context, organizationId string, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PodMutationsAPIGetPodMutatorInstallScript request
	PodMutationsAPIGetPodMutatorInstallScript(ctx context.Context, organizationId string, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PodMutationsAPIListPodMutations(ctx context.Context, organizationId string, clusterId string, params *PodMutationsAPIListPodMutationsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPodMutationsAPIListPodMutationsRequest(c.Server, organizationId, clusterId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PodMutationsAPICreatePodMutationWithBody(ctx context.Context, organizationId string, clusterId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPodMutationsAPICreatePodMutationRequestWithBody(c.Server, organizationId, clusterId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PodMutationsAPICreatePodMutation(ctx context.Context, organizationId string, clusterId string, body PodMutationsAPICreatePodMutationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPodMutationsAPICreatePodMutationRequest(c.Server, organizationId, clusterId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PodMutationsAPIDeletePodMutation(ctx context.Context, organizationId string, clusterId string, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPodMutationsAPIDeletePodMutationRequest(c.Server, organizationId, clusterId, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PodMutationsAPIGetPodMutation(ctx context.Context, organizationId string, clusterId string, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPodMutationsAPIGetPodMutationRequest(c.Server, organizationId, clusterId, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PodMutationsAPIUpdatePodMutationWithBody(ctx context.Context, organizationId string, clusterId string, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPodMutationsAPIUpdatePodMutationRequestWithBody(c.Server, organizationId, clusterId, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PodMutationsAPIUpdatePodMutation(ctx context.Context, organizationId string, clusterId string, id string, body PodMutationsAPIUpdatePodMutationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPodMutationsAPIUpdatePodMutationRequest(c.Server, organizationId, clusterId, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PodMutationsAPIPreviewMatchedWorkloadsWithBody(ctx context.Context, organizationId string, clusterId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPodMutationsAPIPreviewMatchedWorkloadsRequestWithBody(c.Server, organizationId, clusterId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PodMutationsAPIPreviewMatchedWorkloads(ctx context.Context, organizationId string, clusterId string, body PodMutationsAPIPreviewMatchedWorkloadsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPodMutationsAPIPreviewMatchedWorkloadsRequest(c.Server, organizationId, clusterId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PodMutationsAPIGetPodMutatorStatus(ctx context.Context, organizationId string, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPodMutationsAPIGetPodMutatorStatusRequest(c.Server, organizationId, clusterId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PodMutationsAPIListWorkloadPreviews(ctx context.Context, organizationId string, clusterId string, params *PodMutationsAPIListWorkloadPreviewsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPodMutationsAPIListWorkloadPreviewsRequest(c.Server, organizationId, clusterId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PodMutationsAPIGenerateWorkloadPreviewsWithBody(ctx context.Context, organizationId string, clusterId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPodMutationsAPIGenerateWorkloadPreviewsRequestWithBody(c.Server, organizationId, clusterId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PodMutationsAPIGenerateWorkloadPreviews(ctx context.Context, organizationId string, clusterId string, body PodMutationsAPIGenerateWorkloadPreviewsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPodMutationsAPIGenerateWorkloadPreviewsRequest(c.Server, organizationId, clusterId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PodMutationsAPIGetPodMutatorInstallCmd(ctx context.Context, organizationId string, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPodMutationsAPIGetPodMutatorInstallCmdRequest(c.Server, organizationId, clusterId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PodMutationsAPIGetPodMutatorInstallScript(ctx context.Context, organizationId string, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPodMutationsAPIGetPodMutatorInstallScriptRequest(c.Server, organizationId, clusterId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPodMutationsAPIListPodMutationsRequest generates requests for PodMutationsAPIListPodMutations
func NewPodMutationsAPIListPodMutationsRequest(server string, organizationId string, clusterId string, params *PodMutationsAPIListPodMutationsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/patching-engine/v1beta/organizations/%s/clusters/%s/pod-mutations", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.PageLimit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page.limit", runtime.ParamLocationQuery, *params.PageLimit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageCursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page.cursor", runtime.ParamLocationQuery, *params.PageCursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Enabled != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "enabled", runtime.ParamLocationQuery, *params.Enabled); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MaterializePatch != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "materializePatch", runtime.ParamLocationQuery, *params.MaterializePatch); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPodMutationsAPICreatePodMutationRequest calls the generic PodMutationsAPICreatePodMutation builder with application/json body
func NewPodMutationsAPICreatePodMutationRequest(server string, organizationId string, clusterId string, body PodMutationsAPICreatePodMutationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPodMutationsAPICreatePodMutationRequestWithBody(server, organizationId, clusterId, "application/json", bodyReader)
}

// NewPodMutationsAPICreatePodMutationRequestWithBody generates requests for PodMutationsAPICreatePodMutation with any type of body
func NewPodMutationsAPICreatePodMutationRequestWithBody(server string, organizationId string, clusterId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/patching-engine/v1beta/organizations/%s/clusters/%s/pod-mutations", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPodMutationsAPIDeletePodMutationRequest generates requests for PodMutationsAPIDeletePodMutation
func NewPodMutationsAPIDeletePodMutationRequest(server string, organizationId string, clusterId string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/patching-engine/v1beta/organizations/%s/clusters/%s/pod-mutations/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPodMutationsAPIGetPodMutationRequest generates requests for PodMutationsAPIGetPodMutation
func NewPodMutationsAPIGetPodMutationRequest(server string, organizationId string, clusterId string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/patching-engine/v1beta/organizations/%s/clusters/%s/pod-mutations/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPodMutationsAPIUpdatePodMutationRequest calls the generic PodMutationsAPIUpdatePodMutation builder with application/json body
func NewPodMutationsAPIUpdatePodMutationRequest(server string, organizationId string, clusterId string, id string, body PodMutationsAPIUpdatePodMutationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPodMutationsAPIUpdatePodMutationRequestWithBody(server, organizationId, clusterId, id, "application/json", bodyReader)
}

// NewPodMutationsAPIUpdatePodMutationRequestWithBody generates requests for PodMutationsAPIUpdatePodMutation with any type of body
func NewPodMutationsAPIUpdatePodMutationRequestWithBody(server string, organizationId string, clusterId string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/patching-engine/v1beta/organizations/%s/clusters/%s/pod-mutations/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPodMutationsAPIPreviewMatchedWorkloadsRequest calls the generic PodMutationsAPIPreviewMatchedWorkloads builder with application/json body
func NewPodMutationsAPIPreviewMatchedWorkloadsRequest(server string, organizationId string, clusterId string, body PodMutationsAPIPreviewMatchedWorkloadsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPodMutationsAPIPreviewMatchedWorkloadsRequestWithBody(server, organizationId, clusterId, "application/json", bodyReader)
}

// NewPodMutationsAPIPreviewMatchedWorkloadsRequestWithBody generates requests for PodMutationsAPIPreviewMatchedWorkloads with any type of body
func NewPodMutationsAPIPreviewMatchedWorkloadsRequestWithBody(server string, organizationId string, clusterId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/patching-engine/v1beta/organizations/%s/clusters/%s/pod-mutations:previewMatchedWorkloads", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPodMutationsAPIGetPodMutatorStatusRequest generates requests for PodMutationsAPIGetPodMutatorStatus
func NewPodMutationsAPIGetPodMutatorStatusRequest(server string, organizationId string, clusterId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/patching-engine/v1beta/organizations/%s/clusters/%s/pod-mutator-status", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPodMutationsAPIListWorkloadPreviewsRequest generates requests for PodMutationsAPIListWorkloadPreviews
func NewPodMutationsAPIListWorkloadPreviewsRequest(server string, organizationId string, clusterId string, params *PodMutationsAPIListWorkloadPreviewsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/patching-engine/v1beta/organizations/%s/clusters/%s/workload-previews", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.OperationId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "operationId", runtime.ParamLocationQuery, *params.OperationId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.WorkloadType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "workloadType", runtime.ParamLocationQuery, *params.WorkloadType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageLimit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page.limit", runtime.ParamLocationQuery, *params.PageLimit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageCursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page.cursor", runtime.ParamLocationQuery, *params.PageCursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SortField != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sort.field", runtime.ParamLocationQuery, *params.SortField); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SortOrder != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sort.order", runtime.ParamLocationQuery, *params.SortOrder); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FilterNames != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "filter.names", runtime.ParamLocationQuery, *params.FilterNames); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FilterKinds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "filter.kinds", runtime.ParamLocationQuery, *params.FilterKinds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FilterNamespaces != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "filter.namespaces", runtime.ParamLocationQuery, *params.FilterNamespaces); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPodMutationsAPIGenerateWorkloadPreviewsRequest calls the generic PodMutationsAPIGenerateWorkloadPreviews builder with application/json body
func NewPodMutationsAPIGenerateWorkloadPreviewsRequest(server string, organizationId string, clusterId string, body PodMutationsAPIGenerateWorkloadPreviewsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPodMutationsAPIGenerateWorkloadPreviewsRequestWithBody(server, organizationId, clusterId, "application/json", bodyReader)
}

// NewPodMutationsAPIGenerateWorkloadPreviewsRequestWithBody generates requests for PodMutationsAPIGenerateWorkloadPreviews with any type of body
func NewPodMutationsAPIGenerateWorkloadPreviewsRequestWithBody(server string, organizationId string, clusterId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/patching-engine/v1beta/organizations/%s/clusters/%s/workload-previews:generate", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPodMutationsAPIGetPodMutatorInstallCmdRequest generates requests for PodMutationsAPIGetPodMutatorInstallCmd
func NewPodMutationsAPIGetPodMutatorInstallCmdRequest(server string, organizationId string, clusterId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/patching-engine/v1beta/organizations/%s/clusters/%s:getPodMutatorInstallCmd", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPodMutationsAPIGetPodMutatorInstallScriptRequest generates requests for PodMutationsAPIGetPodMutatorInstallScript
func NewPodMutationsAPIGetPodMutatorInstallScriptRequest(server string, organizationId string, clusterId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, organizationId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/patching-engine/v1beta/organizations/%s/clusters/%s:getPodMutatorInstallScript", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	ClientInterface
	// PodMutationsAPIListPodMutations request
	PodMutationsAPIListPodMutationsWithResponse(ctx context.Context, organizationId string, clusterId string, params *PodMutationsAPIListPodMutationsParams) (*PodMutationsAPIListPodMutationsResponse, error)

	// PodMutationsAPICreatePodMutation request  with any body
	PodMutationsAPICreatePodMutationWithBodyWithResponse(ctx context.Context, organizationId string, clusterId string, contentType string, body io.Reader) (*PodMutationsAPICreatePodMutationResponse, error)

	PodMutationsAPICreatePodMutationWithResponse(ctx context.Context, organizationId string, clusterId string, body PodMutationsAPICreatePodMutationJSONRequestBody) (*PodMutationsAPICreatePodMutationResponse, error)

	// PodMutationsAPIDeletePodMutation request
	PodMutationsAPIDeletePodMutationWithResponse(ctx context.Context, organizationId string, clusterId string, id string) (*PodMutationsAPIDeletePodMutationResponse, error)

	// PodMutationsAPIGetPodMutation request
	PodMutationsAPIGetPodMutationWithResponse(ctx context.Context, organizationId string, clusterId string, id string) (*PodMutationsAPIGetPodMutationResponse, error)

	// PodMutationsAPIUpdatePodMutation request  with any body
	PodMutationsAPIUpdatePodMutationWithBodyWithResponse(ctx context.Context, organizationId string, clusterId string, id string, contentType string, body io.Reader) (*PodMutationsAPIUpdatePodMutationResponse, error)

	PodMutationsAPIUpdatePodMutationWithResponse(ctx context.Context, organizationId string, clusterId string, id string, body PodMutationsAPIUpdatePodMutationJSONRequestBody) (*PodMutationsAPIUpdatePodMutationResponse, error)

	// PodMutationsAPIPreviewMatchedWorkloads request  with any body
	PodMutationsAPIPreviewMatchedWorkloadsWithBodyWithResponse(ctx context.Context, organizationId string, clusterId string, contentType string, body io.Reader) (*PodMutationsAPIPreviewMatchedWorkloadsResponse, error)

	PodMutationsAPIPreviewMatchedWorkloadsWithResponse(ctx context.Context, organizationId string, clusterId string, body PodMutationsAPIPreviewMatchedWorkloadsJSONRequestBody) (*PodMutationsAPIPreviewMatchedWorkloadsResponse, error)

	// PodMutationsAPIGetPodMutatorStatus request
	PodMutationsAPIGetPodMutatorStatusWithResponse(ctx context.Context, organizationId string, clusterId string) (*PodMutationsAPIGetPodMutatorStatusResponse, error)

	// PodMutationsAPIListWorkloadPreviews request
	PodMutationsAPIListWorkloadPreviewsWithResponse(ctx context.Context, organizationId string, clusterId string, params *PodMutationsAPIListWorkloadPreviewsParams) (*PodMutationsAPIListWorkloadPreviewsResponse, error)

	// PodMutationsAPIGenerateWorkloadPreviews request  with any body
	PodMutationsAPIGenerateWorkloadPreviewsWithBodyWithResponse(ctx context.Context, organizationId string, clusterId string, contentType string, body io.Reader) (*PodMutationsAPIGenerateWorkloadPreviewsResponse, error)

	PodMutationsAPIGenerateWorkloadPreviewsWithResponse(ctx context.Context, organizationId string, clusterId string, body PodMutationsAPIGenerateWorkloadPreviewsJSONRequestBody) (*PodMutationsAPIGenerateWorkloadPreviewsResponse, error)

	// PodMutationsAPIGetPodMutatorInstallCmd request
	PodMutationsAPIGetPodMutatorInstallCmdWithResponse(ctx context.Context, organizationId string, clusterId string) (*PodMutationsAPIGetPodMutatorInstallCmdResponse, error)

	// PodMutationsAPIGetPodMutatorInstallScript request
	PodMutationsAPIGetPodMutatorInstallScriptWithResponse(ctx context.Context, organizationId string, clusterId string) (*PodMutationsAPIGetPodMutatorInstallScriptResponse, error)
}

// TODO: <castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240
type Response interface {
	Status() string
	StatusCode() int
	GetBody() []byte
}

// TODO: </castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240

type PodMutationsAPIListPodMutationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListPodMutationsResponse
	JSONDefault  *Status
}

// Status returns HTTPResponse.Status
func (r PodMutationsAPIListPodMutationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PodMutationsAPIListPodMutationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// TODO: <castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240
// Body returns body of byte array
func (r PodMutationsAPIListPodMutationsResponse) GetBody() []byte {
	return r.Body
}

// TODO: </castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240

type PodMutationsAPICreatePodMutationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PodMutation
	JSONDefault  *Status
}

// Status returns HTTPResponse.Status
func (r PodMutationsAPICreatePodMutationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PodMutationsAPICreatePodMutationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// TODO: <castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240
// Body returns body of byte array
func (r PodMutationsAPICreatePodMutationResponse) GetBody() []byte {
	return r.Body
}

// TODO: </castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240

type PodMutationsAPIDeletePodMutationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *Status
}

// Status returns HTTPResponse.Status
func (r PodMutationsAPIDeletePodMutationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PodMutationsAPIDeletePodMutationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// TODO: <castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240
// Body returns body of byte array
func (r PodMutationsAPIDeletePodMutationResponse) GetBody() []byte {
	return r.Body
}

// TODO: </castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240

type PodMutationsAPIGetPodMutationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PodMutation
	JSONDefault  *Status
}

// Status returns HTTPResponse.Status
func (r PodMutationsAPIGetPodMutationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PodMutationsAPIGetPodMutationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// TODO: <castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240
// Body returns body of byte array
func (r PodMutationsAPIGetPodMutationResponse) GetBody() []byte {
	return r.Body
}

// TODO: </castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240

type PodMutationsAPIUpdatePodMutationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PodMutation
	JSONDefault  *Status
}

// Status returns HTTPResponse.Status
func (r PodMutationsAPIUpdatePodMutationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PodMutationsAPIUpdatePodMutationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// TODO: <castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240
// Body returns body of byte array
func (r PodMutationsAPIUpdatePodMutationResponse) GetBody() []byte {
	return r.Body
}

// TODO: </castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240

type PodMutationsAPIPreviewMatchedWorkloadsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PreviewMatchedWorkloadsResponse
	JSONDefault  *Status
}

// Status returns HTTPResponse.Status
func (r PodMutationsAPIPreviewMatchedWorkloadsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PodMutationsAPIPreviewMatchedWorkloadsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// TODO: <castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240
// Body returns body of byte array
func (r PodMutationsAPIPreviewMatchedWorkloadsResponse) GetBody() []byte {
	return r.Body
}

// TODO: </castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240

type PodMutationsAPIGetPodMutatorStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PodMutatorStatus
	JSONDefault  *Status
}

// Status returns HTTPResponse.Status
func (r PodMutationsAPIGetPodMutatorStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PodMutationsAPIGetPodMutatorStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// TODO: <castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240
// Body returns body of byte array
func (r PodMutationsAPIGetPodMutatorStatusResponse) GetBody() []byte {
	return r.Body
}

// TODO: </castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240

type PodMutationsAPIListWorkloadPreviewsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListWorkloadPreviewsResponse
	JSONDefault  *Status
}

// Status returns HTTPResponse.Status
func (r PodMutationsAPIListWorkloadPreviewsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PodMutationsAPIListWorkloadPreviewsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// TODO: <castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240
// Body returns body of byte array
func (r PodMutationsAPIListWorkloadPreviewsResponse) GetBody() []byte {
	return r.Body
}

// TODO: </castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240

type PodMutationsAPIGenerateWorkloadPreviewsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *LongRunningOperation
	JSONDefault  *Status
}

// Status returns HTTPResponse.Status
func (r PodMutationsAPIGenerateWorkloadPreviewsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PodMutationsAPIGenerateWorkloadPreviewsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// TODO: <castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240
// Body returns body of byte array
func (r PodMutationsAPIGenerateWorkloadPreviewsResponse) GetBody() []byte {
	return r.Body
}

// TODO: </castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240

type PodMutationsAPIGetPodMutatorInstallCmdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetPodMutatorInstallCmdResponse
	JSONDefault  *Status
}

// Status returns HTTPResponse.Status
func (r PodMutationsAPIGetPodMutatorInstallCmdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PodMutationsAPIGetPodMutatorInstallCmdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// TODO: <castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240
// Body returns body of byte array
func (r PodMutationsAPIGetPodMutatorInstallCmdResponse) GetBody() []byte {
	return r.Body
}

// TODO: </castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240

type PodMutationsAPIGetPodMutatorInstallScriptResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetPodMutatorInstallScriptResponse
	JSONDefault  *Status
}

// Status returns HTTPResponse.Status
func (r PodMutationsAPIGetPodMutatorInstallScriptResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PodMutationsAPIGetPodMutatorInstallScriptResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// TODO: <castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240
// Body returns body of byte array
func (r PodMutationsAPIGetPodMutatorInstallScriptResponse) GetBody() []byte {
	return r.Body
}

// TODO: </castai customization> to have common interface. https://github.com/deepmap/oapi-codegen/issues/240

// PodMutationsAPIListPodMutationsWithResponse request returning *PodMutationsAPIListPodMutationsResponse
func (c *ClientWithResponses) PodMutationsAPIListPodMutationsWithResponse(ctx context.Context, organizationId string, clusterId string, params *PodMutationsAPIListPodMutationsParams) (*PodMutationsAPIListPodMutationsResponse, error) {
	rsp, err := c.PodMutationsAPIListPodMutations(ctx, organizationId, clusterId, params)
	if err != nil {
		return nil, err
	}
	return ParsePodMutationsAPIListPodMutationsResponse(rsp)
}

// PodMutationsAPICreatePodMutationWithBodyWithResponse request with arbitrary body returning *PodMutationsAPICreatePodMutationResponse
func (c *ClientWithResponses) PodMutationsAPICreatePodMutationWithBodyWithResponse(ctx context.Context, organizationId string, clusterId string, contentType string, body io.Reader) (*PodMutationsAPICreatePodMutationResponse, error) {
	rsp, err := c.PodMutationsAPICreatePodMutationWithBody(ctx, organizationId, clusterId, contentType, body)
	if err != nil {
		return nil, err
	}
	return ParsePodMutationsAPICreatePodMutationResponse(rsp)
}

func (c *ClientWithResponses) PodMutationsAPICreatePodMutationWithResponse(ctx context.Context, organizationId string, clusterId string, body PodMutationsAPICreatePodMutationJSONRequestBody) (*PodMutationsAPICreatePodMutationResponse, error) {
	rsp, err := c.PodMutationsAPICreatePodMutation(ctx, organizationId, clusterId, body)
	if err != nil {
		return nil, err
	}
	return ParsePodMutationsAPICreatePodMutationResponse(rsp)
}

// PodMutationsAPIDeletePodMutationWithResponse request returning *PodMutationsAPIDeletePodMutationResponse
func (c *ClientWithResponses) PodMutationsAPIDeletePodMutationWithResponse(ctx context.Context, organizationId string, clusterId string, id string) (*PodMutationsAPIDeletePodMutationResponse, error) {
	rsp, err := c.PodMutationsAPIDeletePodMutation(ctx, organizationId, clusterId, id)
	if err != nil {
		return nil, err
	}
	return ParsePodMutationsAPIDeletePodMutationResponse(rsp)
}

// PodMutationsAPIGetPodMutationWithResponse request returning *PodMutationsAPIGetPodMutationResponse
func (c *ClientWithResponses) PodMutationsAPIGetPodMutationWithResponse(ctx context.Context, organizationId string, clusterId string, id string) (*PodMutationsAPIGetPodMutationResponse, error) {
	rsp, err := c.PodMutationsAPIGetPodMutation(ctx, organizationId, clusterId, id)
	if err != nil {
		return nil, err
	}
	return ParsePodMutationsAPIGetPodMutationResponse(rsp)
}

// PodMutationsAPIUpdatePodMutationWithBodyWithResponse request with arbitrary body returning *PodMutationsAPIUpdatePodMutationResponse
func (c *ClientWithResponses) PodMutationsAPIUpdatePodMutationWithBodyWithResponse(ctx context.Context, organizationId string, clusterId string, id string, contentType string, body io.Reader) (*PodMutationsAPIUpdatePodMutationResponse, error) {
	rsp, err := c.PodMutationsAPIUpdatePodMutationWithBody(ctx, organizationId, clusterId, id, contentType, body)
	if err != nil {
		return nil, err
	}
	return ParsePodMutationsAPIUpdatePodMutationResponse(rsp)
}

func (c *ClientWithResponses) PodMutationsAPIUpdatePodMutationWithResponse(ctx context.Context, organizationId string, clusterId string, id string, body PodMutationsAPIUpdatePodMutationJSONRequestBody) (*PodMutationsAPIUpdatePodMutationResponse, error) {
	rsp, err := c.PodMutationsAPIUpdatePodMutation(ctx, organizationId, clusterId, id, body)
	if err != nil {
		return nil, err
	}
	return ParsePodMutationsAPIUpdatePodMutationResponse(rsp)
}

// PodMutationsAPIPreviewMatchedWorkloadsWithBodyWithResponse request with arbitrary body returning *PodMutationsAPIPreviewMatchedWorkloadsResponse
func (c *ClientWithResponses) PodMutationsAPIPreviewMatchedWorkloadsWithBodyWithResponse(ctx context.Context, organizationId string, clusterId string, contentType string, body io.Reader) (*PodMutationsAPIPreviewMatchedWorkloadsResponse, error) {
	rsp, err := c.PodMutationsAPIPreviewMatchedWorkloadsWithBody(ctx, organizationId, clusterId, contentType, body)
	if err != nil {
		return nil, err
	}
	return ParsePodMutationsAPIPreviewMatchedWorkloadsResponse(rsp)
}

func (c *ClientWithResponses) PodMutationsAPIPreviewMatchedWorkloadsWithResponse(ctx context.Context, organizationId string, clusterId string, body PodMutationsAPIPreviewMatchedWorkloadsJSONRequestBody) (*PodMutationsAPIPreviewMatchedWorkloadsResponse, error) {
	rsp, err := c.PodMutationsAPIPreviewMatchedWorkloads(ctx, organizationId, clusterId, body)
	if err != nil {
		return nil, err
	}
	return ParsePodMutationsAPIPreviewMatchedWorkloadsResponse(rsp)
}

// PodMutationsAPIGetPodMutatorStatusWithResponse request returning *PodMutationsAPIGetPodMutatorStatusResponse
func (c *ClientWithResponses) PodMutationsAPIGetPodMutatorStatusWithResponse(ctx context.Context, organizationId string, clusterId string) (*PodMutationsAPIGetPodMutatorStatusResponse, error) {
	rsp, err := c.PodMutationsAPIGetPodMutatorStatus(ctx, organizationId, clusterId)
	if err != nil {
		return nil, err
	}
	return ParsePodMutationsAPIGetPodMutatorStatusResponse(rsp)
}

// PodMutationsAPIListWorkloadPreviewsWithResponse request returning *PodMutationsAPIListWorkloadPreviewsResponse
func (c *ClientWithResponses) PodMutationsAPIListWorkloadPreviewsWithResponse(ctx context.Context, organizationId string, clusterId string, params *PodMutationsAPIListWorkloadPreviewsParams) (*PodMutationsAPIListWorkloadPreviewsResponse, error) {
	rsp, err := c.PodMutationsAPIListWorkloadPreviews(ctx, organizationId, clusterId, params)
	if err != nil {
		return nil, err
	}
	return ParsePodMutationsAPIListWorkloadPreviewsResponse(rsp)
}

// PodMutationsAPIGenerateWorkloadPreviewsWithBodyWithResponse request with arbitrary body returning *PodMutationsAPIGenerateWorkloadPreviewsResponse
func (c *ClientWithResponses) PodMutationsAPIGenerateWorkloadPreviewsWithBodyWithResponse(ctx context.Context, organizationId string, clusterId string, contentType string, body io.Reader) (*PodMutationsAPIGenerateWorkloadPreviewsResponse, error) {
	rsp, err := c.PodMutationsAPIGenerateWorkloadPreviewsWithBody(ctx, organizationId, clusterId, contentType, body)
	if err != nil {
		return nil, err
	}
	return ParsePodMutationsAPIGenerateWorkloadPreviewsResponse(rsp)
}

func (c *ClientWithResponses) PodMutationsAPIGenerateWorkloadPreviewsWithResponse(ctx context.Context, organizationId string, clusterId string, body PodMutationsAPIGenerateWorkloadPreviewsJSONRequestBody) (*PodMutationsAPIGenerateWorkloadPreviewsResponse, error) {
	rsp, err := c.PodMutationsAPIGenerateWorkloadPreviews(ctx, organizationId, clusterId, body)
	if err != nil {
		return nil, err
	}
	return ParsePodMutationsAPIGenerateWorkloadPreviewsResponse(rsp)
}

// PodMutationsAPIGetPodMutatorInstallCmdWithResponse request returning *PodMutationsAPIGetPodMutatorInstallCmdResponse
func (c *ClientWithResponses) PodMutationsAPIGetPodMutatorInstallCmdWithResponse(ctx context.Context, organizationId string, clusterId string) (*PodMutationsAPIGetPodMutatorInstallCmdResponse, error) {
	rsp, err := c.PodMutationsAPIGetPodMutatorInstallCmd(ctx, organizationId, clusterId)
	if err != nil {
		return nil, err
	}
	return ParsePodMutationsAPIGetPodMutatorInstallCmdResponse(rsp)
}

// PodMutationsAPIGetPodMutatorInstallScriptWithResponse request returning *PodMutationsAPIGetPodMutatorInstallScriptResponse
func (c *ClientWithResponses) PodMutationsAPIGetPodMutatorInstallScriptWithResponse(ctx context.Context, organizationId string, clusterId string) (*PodMutationsAPIGetPodMutatorInstallScriptResponse, error) {
	rsp, err := c.PodMutationsAPIGetPodMutatorInstallScript(ctx, organizationId, clusterId)
	if err != nil {
		return nil, err
	}
	return ParsePodMutationsAPIGetPodMutatorInstallScriptResponse(rsp)
}

// ParsePodMutationsAPIListPodMutationsResponse parses an HTTP response from a PodMutationsAPIListPodMutationsWithResponse call
func ParsePodMutationsAPIListPodMutationsResponse(rsp *http.Response) (*PodMutationsAPIListPodMutationsResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &PodMutationsAPIListPodMutationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListPodMutationsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Status
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePodMutationsAPICreatePodMutationResponse parses an HTTP response from a PodMutationsAPICreatePodMutationWithResponse call
func ParsePodMutationsAPICreatePodMutationResponse(rsp *http.Response) (*PodMutationsAPICreatePodMutationResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &PodMutationsAPICreatePodMutationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PodMutation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Status
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePodMutationsAPIDeletePodMutationResponse parses an HTTP response from a PodMutationsAPIDeletePodMutationWithResponse call
func ParsePodMutationsAPIDeletePodMutationResponse(rsp *http.Response) (*PodMutationsAPIDeletePodMutationResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &PodMutationsAPIDeletePodMutationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Status
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePodMutationsAPIGetPodMutationResponse parses an HTTP response from a PodMutationsAPIGetPodMutationWithResponse call
func ParsePodMutationsAPIGetPodMutationResponse(rsp *http.Response) (*PodMutationsAPIGetPodMutationResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &PodMutationsAPIGetPodMutationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PodMutation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Status
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePodMutationsAPIUpdatePodMutationResponse parses an HTTP response from a PodMutationsAPIUpdatePodMutationWithResponse call
func ParsePodMutationsAPIUpdatePodMutationResponse(rsp *http.Response) (*PodMutationsAPIUpdatePodMutationResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &PodMutationsAPIUpdatePodMutationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PodMutation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Status
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePodMutationsAPIPreviewMatchedWorkloadsResponse parses an HTTP response from a PodMutationsAPIPreviewMatchedWorkloadsWithResponse call
func ParsePodMutationsAPIPreviewMatchedWorkloadsResponse(rsp *http.Response) (*PodMutationsAPIPreviewMatchedWorkloadsResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &PodMutationsAPIPreviewMatchedWorkloadsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PreviewMatchedWorkloadsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Status
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePodMutationsAPIGetPodMutatorStatusResponse parses an HTTP response from a PodMutationsAPIGetPodMutatorStatusWithResponse call
func ParsePodMutationsAPIGetPodMutatorStatusResponse(rsp *http.Response) (*PodMutationsAPIGetPodMutatorStatusResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &PodMutationsAPIGetPodMutatorStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PodMutatorStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Status
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePodMutationsAPIListWorkloadPreviewsResponse parses an HTTP response from a PodMutationsAPIListWorkloadPreviewsWithResponse call
func ParsePodMutationsAPIListWorkloadPreviewsResponse(rsp *http.Response) (*PodMutationsAPIListWorkloadPreviewsResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &PodMutationsAPIListWorkloadPreviewsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListWorkloadPreviewsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Status
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePodMutationsAPIGenerateWorkloadPreviewsResponse parses an HTTP response from a PodMutationsAPIGenerateWorkloadPreviewsWithResponse call
func ParsePodMutationsAPIGenerateWorkloadPreviewsResponse(rsp *http.Response) (*PodMutationsAPIGenerateWorkloadPreviewsResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &PodMutationsAPIGenerateWorkloadPreviewsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LongRunningOperation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Status
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePodMutationsAPIGetPodMutatorInstallCmdResponse parses an HTTP response from a PodMutationsAPIGetPodMutatorInstallCmdWithResponse call
func ParsePodMutationsAPIGetPodMutatorInstallCmdResponse(rsp *http.Response) (*PodMutationsAPIGetPodMutatorInstallCmdResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &PodMutationsAPIGetPodMutatorInstallCmdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetPodMutatorInstallCmdResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Status
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePodMutationsAPIGetPodMutatorInstallScriptResponse parses an HTTP response from a PodMutationsAPIGetPodMutatorInstallScriptWithResponse call
func ParsePodMutationsAPIGetPodMutatorInstallScriptResponse(rsp *http.Response) (*PodMutationsAPIGetPodMutatorInstallScriptResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &PodMutationsAPIGetPodMutatorInstallScriptResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetPodMutatorInstallScriptResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Status
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
