# Example Terragrunt unit that consumes this module.
#
# Copy it into your infrastructure-live repository, e.g.
#   live/prod/us-east-1/my-cluster/castai/terragrunt.hcl
#
# The module is consumed straight from the provider repository; pin `ref` to a tag.

terraform {
  source = "git::https://github.com/castai/terraform-provider-castai.git//examples/eks/eks_cluster_gitops_terragrunt?ref=v8.52.0"
}

locals {
  region       = "us-east-1"
  cluster_name = "my-eks-cluster"
}

# Pull VPC / EKS facts from sibling units instead of hardcoding them.
dependency "eks" {
  config_path = "../eks"

  mock_outputs = {
    cluster_name              = "mock"
    vpc_id                    = "vpc-mock"
    private_subnet_ids        = ["subnet-mock"]
    cluster_security_group_id = "sg-mock"
    node_security_group_id    = "sg-mock"
  }
  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# Providers are usually generated by Terragrunt rather than committed to the module.
# Delete providers.tf from your vendored copy if you use this block.
generate "provider" {
  path      = "provider_override.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    provider "aws" {
      region = "${local.region}"
    }
  EOF
}

inputs = {
  aws_account_id     = get_aws_account_id()
  aws_cluster_region = local.region
  aws_cluster_name   = dependency.eks.outputs.cluster_name
  vpc_id             = dependency.eks.outputs.vpc_id

  # Defaults inherited by every node configuration that does not override them.
  subnets = dependency.eks.outputs.private_subnet_ids
  security_group_ids = [
    dependency.eks.outputs.cluster_security_group_id,
    dependency.eks.outputs.node_security_group_id,
  ]

  castai_api_token = get_env("CASTAI_API_TOKEN")

  # ---------------------------------------------------------------------------
  # Node configurations, keyed by name.
  # ---------------------------------------------------------------------------
  node_configurations = {
    default = {
      disk_cpu_ratio = 0
      min_disk_size  = 100

      eks = {
        # security_groups / instance_profile_arn default to the module-level values.
        imds_v1        = false
        imds_hop_limit = 1
      }

      tags = {
        "managed-by" = "terragrunt"
      }
    }

    # A second configuration, e.g. for workloads that need bigger disks and a
    # dedicated set of subnets.
    storage = {
      disk_cpu_ratio = 5
      min_disk_size  = 500
      subnets        = dependency.eks.outputs.private_subnet_ids

      eks = {
        volume_type       = "gp3"
        volume_iops       = 6000
        volume_throughput = 250
      }
    }
  }

  default_node_configuration = "default"

  # ---------------------------------------------------------------------------
  # Node templates, keyed by name.
  # ---------------------------------------------------------------------------
  node_templates = {
    default-by-castai = {
      is_default   = true
      should_taint = false

      constraints = {
        on_demand = true
      }
    }

    spot = {
      node_configuration = "default"
      should_taint       = true

      custom_labels = {
        type = "spot"
      }

      custom_taints = [
        {
          key    = "dedicated"
          value  = "spot"
          effect = "NoSchedule"
        },
      ]

      constraints = {
        spot                                        = true
        use_spot_fallbacks                          = true
        fallback_restore_rate_seconds               = 1800
        enable_spot_diversity                       = true
        spot_diversity_price_increase_limit_percent = 20
        spot_interruption_predictions_enabled       = true
        spot_interruption_predictions_type          = "interruption-predictions"
        min_cpu                                     = 2
        max_cpu                                     = 16
        min_memory                                  = 4096
        max_memory                                  = 24576
        architectures                               = ["amd64"]

        instance_families = {
          exclude = ["m5"]
        }

        custom_priority = [
          {
            instance_families = ["c5"]
            spot              = true
          },
        ]
      }
    }

    storage-optimized = {
      node_configuration = "storage"
      should_taint       = true

      constraints = {
        on_demand               = true
        storage_optimized_state = "enabled"
      }
    }

    capacity-reservation = {
      is_enabled   = true
      should_taint = false

      constraints = {
        on_demand = true

        aws = {
          capacity_reservations = [
            {
              id   = "cr-12345678901234567"
              type = "ON_DEMAND_CAPACITY_RESERVATION"
            },
          ]
        }
      }
    }
  }

  autoscaler_settings = {
    enabled                = true
    cluster_limits_enabled = true
    cluster_limits_max_cpu = 400
    evictor_enabled        = true
  }
}
