// Package organization_management provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package organization_management

// SCIMSchemaAttribute Represents an attribute in a SCIM schema
//
//	https://datatracker.ietf.org/doc/html/rfc7643#section-2.2
type SCIMSchemaAttribute struct {
	// CaseExact Indicates if the attribute is case exact
	CaseExact *bool `json:"caseExact,omitempty"`

	// Description Description of the attribute
	Description *string `json:"description,omitempty"`

	// MultiValued Multi-valued flag indicating if the attribute can have multiple values
	MultiValued *bool `json:"multiValued,omitempty"`

	// Mutability Mutability of the attribute (readOnly, readWrite, immutable, writeOnly)
	Mutability *string `json:"mutability,omitempty"`

	// Name Name of the attribute
	Name *string `json:"name,omitempty"`

	// ReferenceTypes Reference types for reference attributes
	ReferenceTypes *[]string `json:"referenceTypes,omitempty"`

	// Required Indicates if the attribute is required
	Required *bool `json:"required,omitempty"`

	// Returned Returned value (always, never, default, request)
	Returned *string `json:"returned,omitempty"`

	// SubAttributes Sub-attributes for complex attributes
	SubAttributes *[]SCIMSchemaAttribute `json:"subAttributes,omitempty"`

	// Type Type of the attribute (e.g., string, boolean, complex, reference)
	Type *string `json:"type,omitempty"`

	// Uniqueness Uniqueness of the attribute (none, server, global)
	Uniqueness *string `json:"uniqueness,omitempty"`
}
