// Code generated by MockGen. DO NOT EDIT.
// Source: pricing/client.gen.go

// Package mock_pricing is a generated GoMock package.
package mock_pricing

import (
	context "context"
	io "io"
	http "net/http"
	reflect "reflect"

	pricing "github.com/castai/terraform-provider-castai/castai/sdk/pricing"
	gomock "github.com/golang/mock/gomock"
)

// MockHttpRequestDoer is a mock of HttpRequestDoer interface.
type MockHttpRequestDoer struct {
	ctrl     *gomock.Controller
	recorder *MockHttpRequestDoerMockRecorder
}

// MockHttpRequestDoerMockRecorder is the mock recorder for MockHttpRequestDoer.
type MockHttpRequestDoerMockRecorder struct {
	mock *MockHttpRequestDoer
}

// NewMockHttpRequestDoer creates a new mock instance.
func NewMockHttpRequestDoer(ctrl *gomock.Controller) *MockHttpRequestDoer {
	mock := &MockHttpRequestDoer{ctrl: ctrl}
	mock.recorder = &MockHttpRequestDoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpRequestDoer) EXPECT() *MockHttpRequestDoerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockHttpRequestDoer) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockHttpRequestDoerMockRecorder) Do(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockHttpRequestDoer)(nil).Do), req)
}

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// CommitmentsAPIBatchCreateCommitments mocks base method.
func (m *MockClientInterface) CommitmentsAPIBatchCreateCommitments(ctx context.Context, organizationId string, body pricing.CommitmentsAPIBatchCreateCommitmentsJSONRequestBody, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIBatchCreateCommitments", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIBatchCreateCommitments indicates an expected call of CommitmentsAPIBatchCreateCommitments.
func (mr *MockClientInterfaceMockRecorder) CommitmentsAPIBatchCreateCommitments(ctx, organizationId, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIBatchCreateCommitments", reflect.TypeOf((*MockClientInterface)(nil).CommitmentsAPIBatchCreateCommitments), varargs...)
}

// CommitmentsAPIBatchCreateCommitmentsWithBody mocks base method.
func (m *MockClientInterface) CommitmentsAPIBatchCreateCommitmentsWithBody(ctx context.Context, organizationId, contentType string, body io.Reader, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIBatchCreateCommitmentsWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIBatchCreateCommitmentsWithBody indicates an expected call of CommitmentsAPIBatchCreateCommitmentsWithBody.
func (mr *MockClientInterfaceMockRecorder) CommitmentsAPIBatchCreateCommitmentsWithBody(ctx, organizationId, contentType, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIBatchCreateCommitmentsWithBody", reflect.TypeOf((*MockClientInterface)(nil).CommitmentsAPIBatchCreateCommitmentsWithBody), varargs...)
}

// CommitmentsAPIBatchDeleteCommitments mocks base method.
func (m *MockClientInterface) CommitmentsAPIBatchDeleteCommitments(ctx context.Context, organizationId string, body pricing.CommitmentsAPIBatchDeleteCommitmentsJSONRequestBody, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIBatchDeleteCommitments", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIBatchDeleteCommitments indicates an expected call of CommitmentsAPIBatchDeleteCommitments.
func (mr *MockClientInterfaceMockRecorder) CommitmentsAPIBatchDeleteCommitments(ctx, organizationId, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIBatchDeleteCommitments", reflect.TypeOf((*MockClientInterface)(nil).CommitmentsAPIBatchDeleteCommitments), varargs...)
}

// CommitmentsAPIBatchDeleteCommitmentsWithBody mocks base method.
func (m *MockClientInterface) CommitmentsAPIBatchDeleteCommitmentsWithBody(ctx context.Context, organizationId, contentType string, body io.Reader, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIBatchDeleteCommitmentsWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIBatchDeleteCommitmentsWithBody indicates an expected call of CommitmentsAPIBatchDeleteCommitmentsWithBody.
func (mr *MockClientInterfaceMockRecorder) CommitmentsAPIBatchDeleteCommitmentsWithBody(ctx, organizationId, contentType, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIBatchDeleteCommitmentsWithBody", reflect.TypeOf((*MockClientInterface)(nil).CommitmentsAPIBatchDeleteCommitmentsWithBody), varargs...)
}

// CommitmentsAPIBatchGetCommitmentUsageBreakdowns mocks base method.
func (m *MockClientInterface) CommitmentsAPIBatchGetCommitmentUsageBreakdowns(ctx context.Context, organizationId string, params *pricing.CommitmentsAPIBatchGetCommitmentUsageBreakdownsParams, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIBatchGetCommitmentUsageBreakdowns", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIBatchGetCommitmentUsageBreakdowns indicates an expected call of CommitmentsAPIBatchGetCommitmentUsageBreakdowns.
func (mr *MockClientInterfaceMockRecorder) CommitmentsAPIBatchGetCommitmentUsageBreakdowns(ctx, organizationId, params interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIBatchGetCommitmentUsageBreakdowns", reflect.TypeOf((*MockClientInterface)(nil).CommitmentsAPIBatchGetCommitmentUsageBreakdowns), varargs...)
}

// CommitmentsAPICreateCommitment mocks base method.
func (m *MockClientInterface) CommitmentsAPICreateCommitment(ctx context.Context, organizationId string, body pricing.CommitmentsAPICreateCommitmentJSONRequestBody, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPICreateCommitment", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPICreateCommitment indicates an expected call of CommitmentsAPICreateCommitment.
func (mr *MockClientInterfaceMockRecorder) CommitmentsAPICreateCommitment(ctx, organizationId, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPICreateCommitment", reflect.TypeOf((*MockClientInterface)(nil).CommitmentsAPICreateCommitment), varargs...)
}

// CommitmentsAPICreateCommitmentWithBody mocks base method.
func (m *MockClientInterface) CommitmentsAPICreateCommitmentWithBody(ctx context.Context, organizationId, contentType string, body io.Reader, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPICreateCommitmentWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPICreateCommitmentWithBody indicates an expected call of CommitmentsAPICreateCommitmentWithBody.
func (mr *MockClientInterfaceMockRecorder) CommitmentsAPICreateCommitmentWithBody(ctx, organizationId, contentType, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPICreateCommitmentWithBody", reflect.TypeOf((*MockClientInterface)(nil).CommitmentsAPICreateCommitmentWithBody), varargs...)
}

// CommitmentsAPIDeleteCommitment mocks base method.
func (m *MockClientInterface) CommitmentsAPIDeleteCommitment(ctx context.Context, organizationId, id string, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, id}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIDeleteCommitment", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIDeleteCommitment indicates an expected call of CommitmentsAPIDeleteCommitment.
func (mr *MockClientInterfaceMockRecorder) CommitmentsAPIDeleteCommitment(ctx, organizationId, id interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, id}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIDeleteCommitment", reflect.TypeOf((*MockClientInterface)(nil).CommitmentsAPIDeleteCommitment), varargs...)
}

// CommitmentsAPIGetAzureReservationsImportCommand mocks base method.
func (m *MockClientInterface) CommitmentsAPIGetAzureReservationsImportCommand(ctx context.Context, organizationId string, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIGetAzureReservationsImportCommand", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIGetAzureReservationsImportCommand indicates an expected call of CommitmentsAPIGetAzureReservationsImportCommand.
func (mr *MockClientInterfaceMockRecorder) CommitmentsAPIGetAzureReservationsImportCommand(ctx, organizationId interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIGetAzureReservationsImportCommand", reflect.TypeOf((*MockClientInterface)(nil).CommitmentsAPIGetAzureReservationsImportCommand), varargs...)
}

// CommitmentsAPIGetAzureReservationsImportScript mocks base method.
func (m *MockClientInterface) CommitmentsAPIGetAzureReservationsImportScript(ctx context.Context, organizationId string, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIGetAzureReservationsImportScript", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIGetAzureReservationsImportScript indicates an expected call of CommitmentsAPIGetAzureReservationsImportScript.
func (mr *MockClientInterfaceMockRecorder) CommitmentsAPIGetAzureReservationsImportScript(ctx, organizationId interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIGetAzureReservationsImportScript", reflect.TypeOf((*MockClientInterface)(nil).CommitmentsAPIGetAzureReservationsImportScript), varargs...)
}

// CommitmentsAPIGetCommitment mocks base method.
func (m *MockClientInterface) CommitmentsAPIGetCommitment(ctx context.Context, organizationId, id string, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, id}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIGetCommitment", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIGetCommitment indicates an expected call of CommitmentsAPIGetCommitment.
func (mr *MockClientInterfaceMockRecorder) CommitmentsAPIGetCommitment(ctx, organizationId, id interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, id}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIGetCommitment", reflect.TypeOf((*MockClientInterface)(nil).CommitmentsAPIGetCommitment), varargs...)
}

// CommitmentsAPIGetCommitmentUsageBreakdown mocks base method.
func (m *MockClientInterface) CommitmentsAPIGetCommitmentUsageBreakdown(ctx context.Context, organizationId, commitmentId string, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, commitmentId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIGetCommitmentUsageBreakdown", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIGetCommitmentUsageBreakdown indicates an expected call of CommitmentsAPIGetCommitmentUsageBreakdown.
func (mr *MockClientInterfaceMockRecorder) CommitmentsAPIGetCommitmentUsageBreakdown(ctx, organizationId, commitmentId interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, commitmentId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIGetCommitmentUsageBreakdown", reflect.TypeOf((*MockClientInterface)(nil).CommitmentsAPIGetCommitmentUsageBreakdown), varargs...)
}

// CommitmentsAPIGetUsageSummary mocks base method.
func (m *MockClientInterface) CommitmentsAPIGetUsageSummary(ctx context.Context, organizationId, commitmentId string, params *pricing.CommitmentsAPIGetUsageSummaryParams, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, commitmentId, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIGetUsageSummary", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIGetUsageSummary indicates an expected call of CommitmentsAPIGetUsageSummary.
func (mr *MockClientInterfaceMockRecorder) CommitmentsAPIGetUsageSummary(ctx, organizationId, commitmentId, params interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, commitmentId, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIGetUsageSummary", reflect.TypeOf((*MockClientInterface)(nil).CommitmentsAPIGetUsageSummary), varargs...)
}

// CommitmentsAPIImportAzureReservations mocks base method.
func (m *MockClientInterface) CommitmentsAPIImportAzureReservations(ctx context.Context, organizationId string, params *pricing.CommitmentsAPIImportAzureReservationsParams, body pricing.CommitmentsAPIImportAzureReservationsJSONRequestBody, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, params, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIImportAzureReservations", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIImportAzureReservations indicates an expected call of CommitmentsAPIImportAzureReservations.
func (mr *MockClientInterfaceMockRecorder) CommitmentsAPIImportAzureReservations(ctx, organizationId, params, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, params, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIImportAzureReservations", reflect.TypeOf((*MockClientInterface)(nil).CommitmentsAPIImportAzureReservations), varargs...)
}

// CommitmentsAPIImportAzureReservationsWithBody mocks base method.
func (m *MockClientInterface) CommitmentsAPIImportAzureReservationsWithBody(ctx context.Context, organizationId string, params *pricing.CommitmentsAPIImportAzureReservationsParams, contentType string, body io.Reader, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, params, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIImportAzureReservationsWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIImportAzureReservationsWithBody indicates an expected call of CommitmentsAPIImportAzureReservationsWithBody.
func (mr *MockClientInterfaceMockRecorder) CommitmentsAPIImportAzureReservationsWithBody(ctx, organizationId, params, contentType, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, params, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIImportAzureReservationsWithBody", reflect.TypeOf((*MockClientInterface)(nil).CommitmentsAPIImportAzureReservationsWithBody), varargs...)
}

// CommitmentsAPIListCommitmentAssignments mocks base method.
func (m *MockClientInterface) CommitmentsAPIListCommitmentAssignments(ctx context.Context, organizationId, commitmentId string, params *pricing.CommitmentsAPIListCommitmentAssignmentsParams, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, commitmentId, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIListCommitmentAssignments", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIListCommitmentAssignments indicates an expected call of CommitmentsAPIListCommitmentAssignments.
func (mr *MockClientInterfaceMockRecorder) CommitmentsAPIListCommitmentAssignments(ctx, organizationId, commitmentId, params interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, commitmentId, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIListCommitmentAssignments", reflect.TypeOf((*MockClientInterface)(nil).CommitmentsAPIListCommitmentAssignments), varargs...)
}

// CommitmentsAPIListCommitments mocks base method.
func (m *MockClientInterface) CommitmentsAPIListCommitments(ctx context.Context, organizationId string, params *pricing.CommitmentsAPIListCommitmentsParams, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIListCommitments", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIListCommitments indicates an expected call of CommitmentsAPIListCommitments.
func (mr *MockClientInterfaceMockRecorder) CommitmentsAPIListCommitments(ctx, organizationId, params interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIListCommitments", reflect.TypeOf((*MockClientInterface)(nil).CommitmentsAPIListCommitments), varargs...)
}

// CommitmentsAPIUpdateCommitment mocks base method.
func (m *MockClientInterface) CommitmentsAPIUpdateCommitment(ctx context.Context, organizationId, id string, body pricing.CommitmentsAPIUpdateCommitmentJSONRequestBody, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, id, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIUpdateCommitment", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIUpdateCommitment indicates an expected call of CommitmentsAPIUpdateCommitment.
func (mr *MockClientInterfaceMockRecorder) CommitmentsAPIUpdateCommitment(ctx, organizationId, id, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, id, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIUpdateCommitment", reflect.TypeOf((*MockClientInterface)(nil).CommitmentsAPIUpdateCommitment), varargs...)
}

// CommitmentsAPIUpdateCommitmentWithBody mocks base method.
func (m *MockClientInterface) CommitmentsAPIUpdateCommitmentWithBody(ctx context.Context, organizationId, id, contentType string, body io.Reader, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, id, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIUpdateCommitmentWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIUpdateCommitmentWithBody indicates an expected call of CommitmentsAPIUpdateCommitmentWithBody.
func (mr *MockClientInterfaceMockRecorder) CommitmentsAPIUpdateCommitmentWithBody(ctx, organizationId, id, contentType, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, id, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIUpdateCommitmentWithBody", reflect.TypeOf((*MockClientInterface)(nil).CommitmentsAPIUpdateCommitmentWithBody), varargs...)
}

// MockClientWithResponsesInterface is a mock of ClientWithResponsesInterface interface.
type MockClientWithResponsesInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientWithResponsesInterfaceMockRecorder
}

// MockClientWithResponsesInterfaceMockRecorder is the mock recorder for MockClientWithResponsesInterface.
type MockClientWithResponsesInterfaceMockRecorder struct {
	mock *MockClientWithResponsesInterface
}

// NewMockClientWithResponsesInterface creates a new mock instance.
func NewMockClientWithResponsesInterface(ctrl *gomock.Controller) *MockClientWithResponsesInterface {
	mock := &MockClientWithResponsesInterface{ctrl: ctrl}
	mock.recorder = &MockClientWithResponsesInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientWithResponsesInterface) EXPECT() *MockClientWithResponsesInterfaceMockRecorder {
	return m.recorder
}

// CommitmentsAPIBatchCreateCommitments mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIBatchCreateCommitments(ctx context.Context, organizationId string, body pricing.CommitmentsAPIBatchCreateCommitmentsJSONRequestBody, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIBatchCreateCommitments", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIBatchCreateCommitments indicates an expected call of CommitmentsAPIBatchCreateCommitments.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIBatchCreateCommitments(ctx, organizationId, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIBatchCreateCommitments", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIBatchCreateCommitments), varargs...)
}

// CommitmentsAPIBatchCreateCommitmentsWithBody mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIBatchCreateCommitmentsWithBody(ctx context.Context, organizationId, contentType string, body io.Reader, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIBatchCreateCommitmentsWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIBatchCreateCommitmentsWithBody indicates an expected call of CommitmentsAPIBatchCreateCommitmentsWithBody.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIBatchCreateCommitmentsWithBody(ctx, organizationId, contentType, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIBatchCreateCommitmentsWithBody", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIBatchCreateCommitmentsWithBody), varargs...)
}

// CommitmentsAPIBatchCreateCommitmentsWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIBatchCreateCommitmentsWithBodyWithResponse(ctx context.Context, organizationId, contentType string, body io.Reader) (*pricing.CommitmentsAPIBatchCreateCommitmentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitmentsAPIBatchCreateCommitmentsWithBodyWithResponse", ctx, organizationId, contentType, body)
	ret0, _ := ret[0].(*pricing.CommitmentsAPIBatchCreateCommitmentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIBatchCreateCommitmentsWithBodyWithResponse indicates an expected call of CommitmentsAPIBatchCreateCommitmentsWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIBatchCreateCommitmentsWithBodyWithResponse(ctx, organizationId, contentType, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIBatchCreateCommitmentsWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIBatchCreateCommitmentsWithBodyWithResponse), ctx, organizationId, contentType, body)
}

// CommitmentsAPIBatchCreateCommitmentsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIBatchCreateCommitmentsWithResponse(ctx context.Context, organizationId string, body pricing.CommitmentsAPIBatchCreateCommitmentsJSONRequestBody) (*pricing.CommitmentsAPIBatchCreateCommitmentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitmentsAPIBatchCreateCommitmentsWithResponse", ctx, organizationId, body)
	ret0, _ := ret[0].(*pricing.CommitmentsAPIBatchCreateCommitmentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIBatchCreateCommitmentsWithResponse indicates an expected call of CommitmentsAPIBatchCreateCommitmentsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIBatchCreateCommitmentsWithResponse(ctx, organizationId, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIBatchCreateCommitmentsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIBatchCreateCommitmentsWithResponse), ctx, organizationId, body)
}

// CommitmentsAPIBatchDeleteCommitments mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIBatchDeleteCommitments(ctx context.Context, organizationId string, body pricing.CommitmentsAPIBatchDeleteCommitmentsJSONRequestBody, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIBatchDeleteCommitments", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIBatchDeleteCommitments indicates an expected call of CommitmentsAPIBatchDeleteCommitments.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIBatchDeleteCommitments(ctx, organizationId, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIBatchDeleteCommitments", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIBatchDeleteCommitments), varargs...)
}

// CommitmentsAPIBatchDeleteCommitmentsWithBody mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIBatchDeleteCommitmentsWithBody(ctx context.Context, organizationId, contentType string, body io.Reader, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIBatchDeleteCommitmentsWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIBatchDeleteCommitmentsWithBody indicates an expected call of CommitmentsAPIBatchDeleteCommitmentsWithBody.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIBatchDeleteCommitmentsWithBody(ctx, organizationId, contentType, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIBatchDeleteCommitmentsWithBody", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIBatchDeleteCommitmentsWithBody), varargs...)
}

// CommitmentsAPIBatchDeleteCommitmentsWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIBatchDeleteCommitmentsWithBodyWithResponse(ctx context.Context, organizationId, contentType string, body io.Reader) (*pricing.CommitmentsAPIBatchDeleteCommitmentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitmentsAPIBatchDeleteCommitmentsWithBodyWithResponse", ctx, organizationId, contentType, body)
	ret0, _ := ret[0].(*pricing.CommitmentsAPIBatchDeleteCommitmentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIBatchDeleteCommitmentsWithBodyWithResponse indicates an expected call of CommitmentsAPIBatchDeleteCommitmentsWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIBatchDeleteCommitmentsWithBodyWithResponse(ctx, organizationId, contentType, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIBatchDeleteCommitmentsWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIBatchDeleteCommitmentsWithBodyWithResponse), ctx, organizationId, contentType, body)
}

// CommitmentsAPIBatchDeleteCommitmentsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIBatchDeleteCommitmentsWithResponse(ctx context.Context, organizationId string, body pricing.CommitmentsAPIBatchDeleteCommitmentsJSONRequestBody) (*pricing.CommitmentsAPIBatchDeleteCommitmentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitmentsAPIBatchDeleteCommitmentsWithResponse", ctx, organizationId, body)
	ret0, _ := ret[0].(*pricing.CommitmentsAPIBatchDeleteCommitmentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIBatchDeleteCommitmentsWithResponse indicates an expected call of CommitmentsAPIBatchDeleteCommitmentsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIBatchDeleteCommitmentsWithResponse(ctx, organizationId, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIBatchDeleteCommitmentsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIBatchDeleteCommitmentsWithResponse), ctx, organizationId, body)
}

// CommitmentsAPIBatchGetCommitmentUsageBreakdowns mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIBatchGetCommitmentUsageBreakdowns(ctx context.Context, organizationId string, params *pricing.CommitmentsAPIBatchGetCommitmentUsageBreakdownsParams, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIBatchGetCommitmentUsageBreakdowns", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIBatchGetCommitmentUsageBreakdowns indicates an expected call of CommitmentsAPIBatchGetCommitmentUsageBreakdowns.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIBatchGetCommitmentUsageBreakdowns(ctx, organizationId, params interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIBatchGetCommitmentUsageBreakdowns", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIBatchGetCommitmentUsageBreakdowns), varargs...)
}

// CommitmentsAPIBatchGetCommitmentUsageBreakdownsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIBatchGetCommitmentUsageBreakdownsWithResponse(ctx context.Context, organizationId string, params *pricing.CommitmentsAPIBatchGetCommitmentUsageBreakdownsParams) (*pricing.CommitmentsAPIBatchGetCommitmentUsageBreakdownsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitmentsAPIBatchGetCommitmentUsageBreakdownsWithResponse", ctx, organizationId, params)
	ret0, _ := ret[0].(*pricing.CommitmentsAPIBatchGetCommitmentUsageBreakdownsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIBatchGetCommitmentUsageBreakdownsWithResponse indicates an expected call of CommitmentsAPIBatchGetCommitmentUsageBreakdownsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIBatchGetCommitmentUsageBreakdownsWithResponse(ctx, organizationId, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIBatchGetCommitmentUsageBreakdownsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIBatchGetCommitmentUsageBreakdownsWithResponse), ctx, organizationId, params)
}

// CommitmentsAPICreateCommitment mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPICreateCommitment(ctx context.Context, organizationId string, body pricing.CommitmentsAPICreateCommitmentJSONRequestBody, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPICreateCommitment", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPICreateCommitment indicates an expected call of CommitmentsAPICreateCommitment.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPICreateCommitment(ctx, organizationId, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPICreateCommitment", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPICreateCommitment), varargs...)
}

// CommitmentsAPICreateCommitmentWithBody mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPICreateCommitmentWithBody(ctx context.Context, organizationId, contentType string, body io.Reader, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPICreateCommitmentWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPICreateCommitmentWithBody indicates an expected call of CommitmentsAPICreateCommitmentWithBody.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPICreateCommitmentWithBody(ctx, organizationId, contentType, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPICreateCommitmentWithBody", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPICreateCommitmentWithBody), varargs...)
}

// CommitmentsAPICreateCommitmentWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPICreateCommitmentWithBodyWithResponse(ctx context.Context, organizationId, contentType string, body io.Reader) (*pricing.CommitmentsAPICreateCommitmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitmentsAPICreateCommitmentWithBodyWithResponse", ctx, organizationId, contentType, body)
	ret0, _ := ret[0].(*pricing.CommitmentsAPICreateCommitmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPICreateCommitmentWithBodyWithResponse indicates an expected call of CommitmentsAPICreateCommitmentWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPICreateCommitmentWithBodyWithResponse(ctx, organizationId, contentType, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPICreateCommitmentWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPICreateCommitmentWithBodyWithResponse), ctx, organizationId, contentType, body)
}

// CommitmentsAPICreateCommitmentWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPICreateCommitmentWithResponse(ctx context.Context, organizationId string, body pricing.CommitmentsAPICreateCommitmentJSONRequestBody) (*pricing.CommitmentsAPICreateCommitmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitmentsAPICreateCommitmentWithResponse", ctx, organizationId, body)
	ret0, _ := ret[0].(*pricing.CommitmentsAPICreateCommitmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPICreateCommitmentWithResponse indicates an expected call of CommitmentsAPICreateCommitmentWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPICreateCommitmentWithResponse(ctx, organizationId, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPICreateCommitmentWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPICreateCommitmentWithResponse), ctx, organizationId, body)
}

// CommitmentsAPIDeleteCommitment mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIDeleteCommitment(ctx context.Context, organizationId, id string, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, id}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIDeleteCommitment", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIDeleteCommitment indicates an expected call of CommitmentsAPIDeleteCommitment.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIDeleteCommitment(ctx, organizationId, id interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, id}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIDeleteCommitment", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIDeleteCommitment), varargs...)
}

// CommitmentsAPIDeleteCommitmentWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIDeleteCommitmentWithResponse(ctx context.Context, organizationId, id string) (*pricing.CommitmentsAPIDeleteCommitmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitmentsAPIDeleteCommitmentWithResponse", ctx, organizationId, id)
	ret0, _ := ret[0].(*pricing.CommitmentsAPIDeleteCommitmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIDeleteCommitmentWithResponse indicates an expected call of CommitmentsAPIDeleteCommitmentWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIDeleteCommitmentWithResponse(ctx, organizationId, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIDeleteCommitmentWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIDeleteCommitmentWithResponse), ctx, organizationId, id)
}

// CommitmentsAPIGetAzureReservationsImportCommand mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIGetAzureReservationsImportCommand(ctx context.Context, organizationId string, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIGetAzureReservationsImportCommand", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIGetAzureReservationsImportCommand indicates an expected call of CommitmentsAPIGetAzureReservationsImportCommand.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIGetAzureReservationsImportCommand(ctx, organizationId interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIGetAzureReservationsImportCommand", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIGetAzureReservationsImportCommand), varargs...)
}

// CommitmentsAPIGetAzureReservationsImportCommandWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIGetAzureReservationsImportCommandWithResponse(ctx context.Context, organizationId string) (*pricing.CommitmentsAPIGetAzureReservationsImportCommandResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitmentsAPIGetAzureReservationsImportCommandWithResponse", ctx, organizationId)
	ret0, _ := ret[0].(*pricing.CommitmentsAPIGetAzureReservationsImportCommandResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIGetAzureReservationsImportCommandWithResponse indicates an expected call of CommitmentsAPIGetAzureReservationsImportCommandWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIGetAzureReservationsImportCommandWithResponse(ctx, organizationId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIGetAzureReservationsImportCommandWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIGetAzureReservationsImportCommandWithResponse), ctx, organizationId)
}

// CommitmentsAPIGetAzureReservationsImportScript mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIGetAzureReservationsImportScript(ctx context.Context, organizationId string, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIGetAzureReservationsImportScript", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIGetAzureReservationsImportScript indicates an expected call of CommitmentsAPIGetAzureReservationsImportScript.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIGetAzureReservationsImportScript(ctx, organizationId interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIGetAzureReservationsImportScript", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIGetAzureReservationsImportScript), varargs...)
}

// CommitmentsAPIGetAzureReservationsImportScriptWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIGetAzureReservationsImportScriptWithResponse(ctx context.Context, organizationId string) (*pricing.CommitmentsAPIGetAzureReservationsImportScriptResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitmentsAPIGetAzureReservationsImportScriptWithResponse", ctx, organizationId)
	ret0, _ := ret[0].(*pricing.CommitmentsAPIGetAzureReservationsImportScriptResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIGetAzureReservationsImportScriptWithResponse indicates an expected call of CommitmentsAPIGetAzureReservationsImportScriptWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIGetAzureReservationsImportScriptWithResponse(ctx, organizationId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIGetAzureReservationsImportScriptWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIGetAzureReservationsImportScriptWithResponse), ctx, organizationId)
}

// CommitmentsAPIGetCommitment mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIGetCommitment(ctx context.Context, organizationId, id string, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, id}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIGetCommitment", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIGetCommitment indicates an expected call of CommitmentsAPIGetCommitment.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIGetCommitment(ctx, organizationId, id interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, id}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIGetCommitment", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIGetCommitment), varargs...)
}

// CommitmentsAPIGetCommitmentUsageBreakdown mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIGetCommitmentUsageBreakdown(ctx context.Context, organizationId, commitmentId string, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, commitmentId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIGetCommitmentUsageBreakdown", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIGetCommitmentUsageBreakdown indicates an expected call of CommitmentsAPIGetCommitmentUsageBreakdown.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIGetCommitmentUsageBreakdown(ctx, organizationId, commitmentId interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, commitmentId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIGetCommitmentUsageBreakdown", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIGetCommitmentUsageBreakdown), varargs...)
}

// CommitmentsAPIGetCommitmentUsageBreakdownWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIGetCommitmentUsageBreakdownWithResponse(ctx context.Context, organizationId, commitmentId string) (*pricing.CommitmentsAPIGetCommitmentUsageBreakdownResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitmentsAPIGetCommitmentUsageBreakdownWithResponse", ctx, organizationId, commitmentId)
	ret0, _ := ret[0].(*pricing.CommitmentsAPIGetCommitmentUsageBreakdownResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIGetCommitmentUsageBreakdownWithResponse indicates an expected call of CommitmentsAPIGetCommitmentUsageBreakdownWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIGetCommitmentUsageBreakdownWithResponse(ctx, organizationId, commitmentId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIGetCommitmentUsageBreakdownWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIGetCommitmentUsageBreakdownWithResponse), ctx, organizationId, commitmentId)
}

// CommitmentsAPIGetCommitmentWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIGetCommitmentWithResponse(ctx context.Context, organizationId, id string) (*pricing.CommitmentsAPIGetCommitmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitmentsAPIGetCommitmentWithResponse", ctx, organizationId, id)
	ret0, _ := ret[0].(*pricing.CommitmentsAPIGetCommitmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIGetCommitmentWithResponse indicates an expected call of CommitmentsAPIGetCommitmentWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIGetCommitmentWithResponse(ctx, organizationId, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIGetCommitmentWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIGetCommitmentWithResponse), ctx, organizationId, id)
}

// CommitmentsAPIGetUsageSummary mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIGetUsageSummary(ctx context.Context, organizationId, commitmentId string, params *pricing.CommitmentsAPIGetUsageSummaryParams, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, commitmentId, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIGetUsageSummary", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIGetUsageSummary indicates an expected call of CommitmentsAPIGetUsageSummary.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIGetUsageSummary(ctx, organizationId, commitmentId, params interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, commitmentId, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIGetUsageSummary", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIGetUsageSummary), varargs...)
}

// CommitmentsAPIGetUsageSummaryWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIGetUsageSummaryWithResponse(ctx context.Context, organizationId, commitmentId string, params *pricing.CommitmentsAPIGetUsageSummaryParams) (*pricing.CommitmentsAPIGetUsageSummaryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitmentsAPIGetUsageSummaryWithResponse", ctx, organizationId, commitmentId, params)
	ret0, _ := ret[0].(*pricing.CommitmentsAPIGetUsageSummaryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIGetUsageSummaryWithResponse indicates an expected call of CommitmentsAPIGetUsageSummaryWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIGetUsageSummaryWithResponse(ctx, organizationId, commitmentId, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIGetUsageSummaryWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIGetUsageSummaryWithResponse), ctx, organizationId, commitmentId, params)
}

// CommitmentsAPIImportAzureReservations mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIImportAzureReservations(ctx context.Context, organizationId string, params *pricing.CommitmentsAPIImportAzureReservationsParams, body pricing.CommitmentsAPIImportAzureReservationsJSONRequestBody, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, params, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIImportAzureReservations", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIImportAzureReservations indicates an expected call of CommitmentsAPIImportAzureReservations.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIImportAzureReservations(ctx, organizationId, params, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, params, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIImportAzureReservations", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIImportAzureReservations), varargs...)
}

// CommitmentsAPIImportAzureReservationsWithBody mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIImportAzureReservationsWithBody(ctx context.Context, organizationId string, params *pricing.CommitmentsAPIImportAzureReservationsParams, contentType string, body io.Reader, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, params, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIImportAzureReservationsWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIImportAzureReservationsWithBody indicates an expected call of CommitmentsAPIImportAzureReservationsWithBody.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIImportAzureReservationsWithBody(ctx, organizationId, params, contentType, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, params, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIImportAzureReservationsWithBody", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIImportAzureReservationsWithBody), varargs...)
}

// CommitmentsAPIImportAzureReservationsWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIImportAzureReservationsWithBodyWithResponse(ctx context.Context, organizationId string, params *pricing.CommitmentsAPIImportAzureReservationsParams, contentType string, body io.Reader) (*pricing.CommitmentsAPIImportAzureReservationsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitmentsAPIImportAzureReservationsWithBodyWithResponse", ctx, organizationId, params, contentType, body)
	ret0, _ := ret[0].(*pricing.CommitmentsAPIImportAzureReservationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIImportAzureReservationsWithBodyWithResponse indicates an expected call of CommitmentsAPIImportAzureReservationsWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIImportAzureReservationsWithBodyWithResponse(ctx, organizationId, params, contentType, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIImportAzureReservationsWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIImportAzureReservationsWithBodyWithResponse), ctx, organizationId, params, contentType, body)
}

// CommitmentsAPIImportAzureReservationsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIImportAzureReservationsWithResponse(ctx context.Context, organizationId string, params *pricing.CommitmentsAPIImportAzureReservationsParams, body pricing.CommitmentsAPIImportAzureReservationsJSONRequestBody) (*pricing.CommitmentsAPIImportAzureReservationsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitmentsAPIImportAzureReservationsWithResponse", ctx, organizationId, params, body)
	ret0, _ := ret[0].(*pricing.CommitmentsAPIImportAzureReservationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIImportAzureReservationsWithResponse indicates an expected call of CommitmentsAPIImportAzureReservationsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIImportAzureReservationsWithResponse(ctx, organizationId, params, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIImportAzureReservationsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIImportAzureReservationsWithResponse), ctx, organizationId, params, body)
}

// CommitmentsAPIListCommitmentAssignments mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIListCommitmentAssignments(ctx context.Context, organizationId, commitmentId string, params *pricing.CommitmentsAPIListCommitmentAssignmentsParams, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, commitmentId, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIListCommitmentAssignments", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIListCommitmentAssignments indicates an expected call of CommitmentsAPIListCommitmentAssignments.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIListCommitmentAssignments(ctx, organizationId, commitmentId, params interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, commitmentId, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIListCommitmentAssignments", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIListCommitmentAssignments), varargs...)
}

// CommitmentsAPIListCommitmentAssignmentsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIListCommitmentAssignmentsWithResponse(ctx context.Context, organizationId, commitmentId string, params *pricing.CommitmentsAPIListCommitmentAssignmentsParams) (*pricing.CommitmentsAPIListCommitmentAssignmentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitmentsAPIListCommitmentAssignmentsWithResponse", ctx, organizationId, commitmentId, params)
	ret0, _ := ret[0].(*pricing.CommitmentsAPIListCommitmentAssignmentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIListCommitmentAssignmentsWithResponse indicates an expected call of CommitmentsAPIListCommitmentAssignmentsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIListCommitmentAssignmentsWithResponse(ctx, organizationId, commitmentId, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIListCommitmentAssignmentsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIListCommitmentAssignmentsWithResponse), ctx, organizationId, commitmentId, params)
}

// CommitmentsAPIListCommitments mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIListCommitments(ctx context.Context, organizationId string, params *pricing.CommitmentsAPIListCommitmentsParams, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIListCommitments", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIListCommitments indicates an expected call of CommitmentsAPIListCommitments.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIListCommitments(ctx, organizationId, params interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIListCommitments", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIListCommitments), varargs...)
}

// CommitmentsAPIListCommitmentsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIListCommitmentsWithResponse(ctx context.Context, organizationId string, params *pricing.CommitmentsAPIListCommitmentsParams) (*pricing.CommitmentsAPIListCommitmentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitmentsAPIListCommitmentsWithResponse", ctx, organizationId, params)
	ret0, _ := ret[0].(*pricing.CommitmentsAPIListCommitmentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIListCommitmentsWithResponse indicates an expected call of CommitmentsAPIListCommitmentsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIListCommitmentsWithResponse(ctx, organizationId, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIListCommitmentsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIListCommitmentsWithResponse), ctx, organizationId, params)
}

// CommitmentsAPIUpdateCommitment mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIUpdateCommitment(ctx context.Context, organizationId, id string, body pricing.CommitmentsAPIUpdateCommitmentJSONRequestBody, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, id, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIUpdateCommitment", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIUpdateCommitment indicates an expected call of CommitmentsAPIUpdateCommitment.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIUpdateCommitment(ctx, organizationId, id, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, id, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIUpdateCommitment", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIUpdateCommitment), varargs...)
}

// CommitmentsAPIUpdateCommitmentWithBody mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIUpdateCommitmentWithBody(ctx context.Context, organizationId, id, contentType string, body io.Reader, reqEditors ...pricing.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, id, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitmentsAPIUpdateCommitmentWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIUpdateCommitmentWithBody indicates an expected call of CommitmentsAPIUpdateCommitmentWithBody.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIUpdateCommitmentWithBody(ctx, organizationId, id, contentType, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, id, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIUpdateCommitmentWithBody", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIUpdateCommitmentWithBody), varargs...)
}

// CommitmentsAPIUpdateCommitmentWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIUpdateCommitmentWithBodyWithResponse(ctx context.Context, organizationId, id, contentType string, body io.Reader) (*pricing.CommitmentsAPIUpdateCommitmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitmentsAPIUpdateCommitmentWithBodyWithResponse", ctx, organizationId, id, contentType, body)
	ret0, _ := ret[0].(*pricing.CommitmentsAPIUpdateCommitmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIUpdateCommitmentWithBodyWithResponse indicates an expected call of CommitmentsAPIUpdateCommitmentWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIUpdateCommitmentWithBodyWithResponse(ctx, organizationId, id, contentType, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIUpdateCommitmentWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIUpdateCommitmentWithBodyWithResponse), ctx, organizationId, id, contentType, body)
}

// CommitmentsAPIUpdateCommitmentWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) CommitmentsAPIUpdateCommitmentWithResponse(ctx context.Context, organizationId, id string, body pricing.CommitmentsAPIUpdateCommitmentJSONRequestBody) (*pricing.CommitmentsAPIUpdateCommitmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitmentsAPIUpdateCommitmentWithResponse", ctx, organizationId, id, body)
	ret0, _ := ret[0].(*pricing.CommitmentsAPIUpdateCommitmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitmentsAPIUpdateCommitmentWithResponse indicates an expected call of CommitmentsAPIUpdateCommitmentWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) CommitmentsAPIUpdateCommitmentWithResponse(ctx, organizationId, id, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitmentsAPIUpdateCommitmentWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).CommitmentsAPIUpdateCommitmentWithResponse), ctx, organizationId, id, body)
}

// MockResponse is a mock of Response interface.
type MockResponse struct {
	ctrl     *gomock.Controller
	recorder *MockResponseMockRecorder
}

// MockResponseMockRecorder is the mock recorder for MockResponse.
type MockResponseMockRecorder struct {
	mock *MockResponse
}

// NewMockResponse creates a new mock instance.
func NewMockResponse(ctrl *gomock.Controller) *MockResponse {
	mock := &MockResponse{ctrl: ctrl}
	mock.recorder = &MockResponseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponse) EXPECT() *MockResponseMockRecorder {
	return m.recorder
}

// GetBody mocks base method.
func (m *MockResponse) GetBody() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBody")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetBody indicates an expected call of GetBody.
func (mr *MockResponseMockRecorder) GetBody() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBody", reflect.TypeOf((*MockResponse)(nil).GetBody))
}

// Status mocks base method.
func (m *MockResponse) Status() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(string)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockResponseMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockResponse)(nil).Status))
}

// StatusCode mocks base method.
func (m *MockResponse) StatusCode() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusCode")
	ret0, _ := ret[0].(int)
	return ret0
}

// StatusCode indicates an expected call of StatusCode.
func (mr *MockResponseMockRecorder) StatusCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusCode", reflect.TypeOf((*MockResponse)(nil).StatusCode))
}
