// Code generated by MockGen. DO NOT EDIT.
// Source: external_connections/client.gen.go

// Package mock_external_connections is a generated GoMock package.
package mock_external_connections

import (
	context "context"
	io "io"
	http "net/http"
	reflect "reflect"

	external_connections "github.com/castai/terraform-provider-castai/castai/sdk/external_connections"
	gomock "github.com/golang/mock/gomock"
)

// MockHttpRequestDoer is a mock of HttpRequestDoer interface.
type MockHttpRequestDoer struct {
	ctrl     *gomock.Controller
	recorder *MockHttpRequestDoerMockRecorder
}

// MockHttpRequestDoerMockRecorder is the mock recorder for MockHttpRequestDoer.
type MockHttpRequestDoerMockRecorder struct {
	mock *MockHttpRequestDoer
}

// NewMockHttpRequestDoer creates a new mock instance.
func NewMockHttpRequestDoer(ctrl *gomock.Controller) *MockHttpRequestDoer {
	mock := &MockHttpRequestDoer{ctrl: ctrl}
	mock.recorder = &MockHttpRequestDoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpRequestDoer) EXPECT() *MockHttpRequestDoerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockHttpRequestDoer) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockHttpRequestDoerMockRecorder) Do(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockHttpRequestDoer)(nil).Do), req)
}

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// ExternalConnectionsAPIComputePermissions mocks base method.
func (m *MockClientInterface) ExternalConnectionsAPIComputePermissions(ctx context.Context, body external_connections.ExternalConnectionsAPIComputePermissionsJSONRequestBody, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIComputePermissions", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIComputePermissions indicates an expected call of ExternalConnectionsAPIComputePermissions.
func (mr *MockClientInterfaceMockRecorder) ExternalConnectionsAPIComputePermissions(ctx, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIComputePermissions", reflect.TypeOf((*MockClientInterface)(nil).ExternalConnectionsAPIComputePermissions), varargs...)
}

// ExternalConnectionsAPIComputePermissionsWithBody mocks base method.
func (m *MockClientInterface) ExternalConnectionsAPIComputePermissionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIComputePermissionsWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIComputePermissionsWithBody indicates an expected call of ExternalConnectionsAPIComputePermissionsWithBody.
func (mr *MockClientInterfaceMockRecorder) ExternalConnectionsAPIComputePermissionsWithBody(ctx, contentType, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIComputePermissionsWithBody", reflect.TypeOf((*MockClientInterface)(nil).ExternalConnectionsAPIComputePermissionsWithBody), varargs...)
}

// ExternalConnectionsAPIDeleteConnection mocks base method.
func (m *MockClientInterface) ExternalConnectionsAPIDeleteConnection(ctx context.Context, organizationId, id string, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, id}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIDeleteConnection", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIDeleteConnection indicates an expected call of ExternalConnectionsAPIDeleteConnection.
func (mr *MockClientInterfaceMockRecorder) ExternalConnectionsAPIDeleteConnection(ctx, organizationId, id interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, id}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIDeleteConnection", reflect.TypeOf((*MockClientInterface)(nil).ExternalConnectionsAPIDeleteConnection), varargs...)
}

// ExternalConnectionsAPIGetConnection mocks base method.
func (m *MockClientInterface) ExternalConnectionsAPIGetConnection(ctx context.Context, organizationId, id string, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, id}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIGetConnection", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIGetConnection indicates an expected call of ExternalConnectionsAPIGetConnection.
func (mr *MockClientInterfaceMockRecorder) ExternalConnectionsAPIGetConnection(ctx, organizationId, id interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, id}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIGetConnection", reflect.TypeOf((*MockClientInterface)(nil).ExternalConnectionsAPIGetConnection), varargs...)
}

// ExternalConnectionsAPIGetOnboardingCommand mocks base method.
func (m *MockClientInterface) ExternalConnectionsAPIGetOnboardingCommand(ctx context.Context, organizationId string, body external_connections.ExternalConnectionsAPIGetOnboardingCommandJSONRequestBody, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIGetOnboardingCommand", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIGetOnboardingCommand indicates an expected call of ExternalConnectionsAPIGetOnboardingCommand.
func (mr *MockClientInterfaceMockRecorder) ExternalConnectionsAPIGetOnboardingCommand(ctx, organizationId, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIGetOnboardingCommand", reflect.TypeOf((*MockClientInterface)(nil).ExternalConnectionsAPIGetOnboardingCommand), varargs...)
}

// ExternalConnectionsAPIGetOnboardingCommandWithBody mocks base method.
func (m *MockClientInterface) ExternalConnectionsAPIGetOnboardingCommandWithBody(ctx context.Context, organizationId, contentType string, body io.Reader, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIGetOnboardingCommandWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIGetOnboardingCommandWithBody indicates an expected call of ExternalConnectionsAPIGetOnboardingCommandWithBody.
func (mr *MockClientInterfaceMockRecorder) ExternalConnectionsAPIGetOnboardingCommandWithBody(ctx, organizationId, contentType, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIGetOnboardingCommandWithBody", reflect.TypeOf((*MockClientInterface)(nil).ExternalConnectionsAPIGetOnboardingCommandWithBody), varargs...)
}

// ExternalConnectionsAPIListConnections mocks base method.
func (m *MockClientInterface) ExternalConnectionsAPIListConnections(ctx context.Context, organizationId string, params *external_connections.ExternalConnectionsAPIListConnectionsParams, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIListConnections", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIListConnections indicates an expected call of ExternalConnectionsAPIListConnections.
func (mr *MockClientInterfaceMockRecorder) ExternalConnectionsAPIListConnections(ctx, organizationId, params interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIListConnections", reflect.TypeOf((*MockClientInterface)(nil).ExternalConnectionsAPIListConnections), varargs...)
}

// ExternalConnectionsAPIListFeatures mocks base method.
func (m *MockClientInterface) ExternalConnectionsAPIListFeatures(ctx context.Context, params *external_connections.ExternalConnectionsAPIListFeaturesParams, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIListFeatures", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIListFeatures indicates an expected call of ExternalConnectionsAPIListFeatures.
func (mr *MockClientInterfaceMockRecorder) ExternalConnectionsAPIListFeatures(ctx, params interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIListFeatures", reflect.TypeOf((*MockClientInterface)(nil).ExternalConnectionsAPIListFeatures), varargs...)
}

// ExternalConnectionsAPIProvisionCastPrincipals mocks base method.
func (m *MockClientInterface) ExternalConnectionsAPIProvisionCastPrincipals(ctx context.Context, organizationId string, body external_connections.ExternalConnectionsAPIProvisionCastPrincipalsJSONRequestBody, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIProvisionCastPrincipals", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIProvisionCastPrincipals indicates an expected call of ExternalConnectionsAPIProvisionCastPrincipals.
func (mr *MockClientInterfaceMockRecorder) ExternalConnectionsAPIProvisionCastPrincipals(ctx, organizationId, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIProvisionCastPrincipals", reflect.TypeOf((*MockClientInterface)(nil).ExternalConnectionsAPIProvisionCastPrincipals), varargs...)
}

// ExternalConnectionsAPIProvisionCastPrincipalsWithBody mocks base method.
func (m *MockClientInterface) ExternalConnectionsAPIProvisionCastPrincipalsWithBody(ctx context.Context, organizationId, contentType string, body io.Reader, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIProvisionCastPrincipalsWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIProvisionCastPrincipalsWithBody indicates an expected call of ExternalConnectionsAPIProvisionCastPrincipalsWithBody.
func (mr *MockClientInterfaceMockRecorder) ExternalConnectionsAPIProvisionCastPrincipalsWithBody(ctx, organizationId, contentType, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIProvisionCastPrincipalsWithBody", reflect.TypeOf((*MockClientInterface)(nil).ExternalConnectionsAPIProvisionCastPrincipalsWithBody), varargs...)
}

// ExternalConnectionsAPIUpsertConnection mocks base method.
func (m *MockClientInterface) ExternalConnectionsAPIUpsertConnection(ctx context.Context, organizationId string, body external_connections.ExternalConnectionsAPIUpsertConnectionJSONRequestBody, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIUpsertConnection", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIUpsertConnection indicates an expected call of ExternalConnectionsAPIUpsertConnection.
func (mr *MockClientInterfaceMockRecorder) ExternalConnectionsAPIUpsertConnection(ctx, organizationId, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIUpsertConnection", reflect.TypeOf((*MockClientInterface)(nil).ExternalConnectionsAPIUpsertConnection), varargs...)
}

// ExternalConnectionsAPIUpsertConnectionWithBody mocks base method.
func (m *MockClientInterface) ExternalConnectionsAPIUpsertConnectionWithBody(ctx context.Context, organizationId, contentType string, body io.Reader, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIUpsertConnectionWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIUpsertConnectionWithBody indicates an expected call of ExternalConnectionsAPIUpsertConnectionWithBody.
func (mr *MockClientInterfaceMockRecorder) ExternalConnectionsAPIUpsertConnectionWithBody(ctx, organizationId, contentType, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIUpsertConnectionWithBody", reflect.TypeOf((*MockClientInterface)(nil).ExternalConnectionsAPIUpsertConnectionWithBody), varargs...)
}

// MockClientWithResponsesInterface is a mock of ClientWithResponsesInterface interface.
type MockClientWithResponsesInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientWithResponsesInterfaceMockRecorder
}

// MockClientWithResponsesInterfaceMockRecorder is the mock recorder for MockClientWithResponsesInterface.
type MockClientWithResponsesInterfaceMockRecorder struct {
	mock *MockClientWithResponsesInterface
}

// NewMockClientWithResponsesInterface creates a new mock instance.
func NewMockClientWithResponsesInterface(ctrl *gomock.Controller) *MockClientWithResponsesInterface {
	mock := &MockClientWithResponsesInterface{ctrl: ctrl}
	mock.recorder = &MockClientWithResponsesInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientWithResponsesInterface) EXPECT() *MockClientWithResponsesInterfaceMockRecorder {
	return m.recorder
}

// ExternalConnectionsAPIComputePermissions mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIComputePermissions(ctx context.Context, body external_connections.ExternalConnectionsAPIComputePermissionsJSONRequestBody, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIComputePermissions", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIComputePermissions indicates an expected call of ExternalConnectionsAPIComputePermissions.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIComputePermissions(ctx, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIComputePermissions", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIComputePermissions), varargs...)
}

// ExternalConnectionsAPIComputePermissionsWithBody mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIComputePermissionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIComputePermissionsWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIComputePermissionsWithBody indicates an expected call of ExternalConnectionsAPIComputePermissionsWithBody.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIComputePermissionsWithBody(ctx, contentType, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIComputePermissionsWithBody", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIComputePermissionsWithBody), varargs...)
}

// ExternalConnectionsAPIComputePermissionsWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIComputePermissionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader) (*external_connections.ExternalConnectionsAPIComputePermissionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIComputePermissionsWithBodyWithResponse", ctx, contentType, body)
	ret0, _ := ret[0].(*external_connections.ExternalConnectionsAPIComputePermissionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIComputePermissionsWithBodyWithResponse indicates an expected call of ExternalConnectionsAPIComputePermissionsWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIComputePermissionsWithBodyWithResponse(ctx, contentType, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIComputePermissionsWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIComputePermissionsWithBodyWithResponse), ctx, contentType, body)
}

// ExternalConnectionsAPIComputePermissionsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIComputePermissionsWithResponse(ctx context.Context, body external_connections.ExternalConnectionsAPIComputePermissionsJSONRequestBody) (*external_connections.ExternalConnectionsAPIComputePermissionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIComputePermissionsWithResponse", ctx, body)
	ret0, _ := ret[0].(*external_connections.ExternalConnectionsAPIComputePermissionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIComputePermissionsWithResponse indicates an expected call of ExternalConnectionsAPIComputePermissionsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIComputePermissionsWithResponse(ctx, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIComputePermissionsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIComputePermissionsWithResponse), ctx, body)
}

// ExternalConnectionsAPIDeleteConnection mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIDeleteConnection(ctx context.Context, organizationId, id string, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, id}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIDeleteConnection", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIDeleteConnection indicates an expected call of ExternalConnectionsAPIDeleteConnection.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIDeleteConnection(ctx, organizationId, id interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, id}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIDeleteConnection", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIDeleteConnection), varargs...)
}

// ExternalConnectionsAPIDeleteConnectionWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIDeleteConnectionWithResponse(ctx context.Context, organizationId, id string) (*external_connections.ExternalConnectionsAPIDeleteConnectionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIDeleteConnectionWithResponse", ctx, organizationId, id)
	ret0, _ := ret[0].(*external_connections.ExternalConnectionsAPIDeleteConnectionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIDeleteConnectionWithResponse indicates an expected call of ExternalConnectionsAPIDeleteConnectionWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIDeleteConnectionWithResponse(ctx, organizationId, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIDeleteConnectionWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIDeleteConnectionWithResponse), ctx, organizationId, id)
}

// ExternalConnectionsAPIGetConnection mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIGetConnection(ctx context.Context, organizationId, id string, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, id}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIGetConnection", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIGetConnection indicates an expected call of ExternalConnectionsAPIGetConnection.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIGetConnection(ctx, organizationId, id interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, id}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIGetConnection", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIGetConnection), varargs...)
}

// ExternalConnectionsAPIGetConnectionWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIGetConnectionWithResponse(ctx context.Context, organizationId, id string) (*external_connections.ExternalConnectionsAPIGetConnectionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIGetConnectionWithResponse", ctx, organizationId, id)
	ret0, _ := ret[0].(*external_connections.ExternalConnectionsAPIGetConnectionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIGetConnectionWithResponse indicates an expected call of ExternalConnectionsAPIGetConnectionWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIGetConnectionWithResponse(ctx, organizationId, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIGetConnectionWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIGetConnectionWithResponse), ctx, organizationId, id)
}

// ExternalConnectionsAPIGetOnboardingCommand mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIGetOnboardingCommand(ctx context.Context, organizationId string, body external_connections.ExternalConnectionsAPIGetOnboardingCommandJSONRequestBody, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIGetOnboardingCommand", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIGetOnboardingCommand indicates an expected call of ExternalConnectionsAPIGetOnboardingCommand.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIGetOnboardingCommand(ctx, organizationId, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIGetOnboardingCommand", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIGetOnboardingCommand), varargs...)
}

// ExternalConnectionsAPIGetOnboardingCommandWithBody mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIGetOnboardingCommandWithBody(ctx context.Context, organizationId, contentType string, body io.Reader, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIGetOnboardingCommandWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIGetOnboardingCommandWithBody indicates an expected call of ExternalConnectionsAPIGetOnboardingCommandWithBody.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIGetOnboardingCommandWithBody(ctx, organizationId, contentType, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIGetOnboardingCommandWithBody", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIGetOnboardingCommandWithBody), varargs...)
}

// ExternalConnectionsAPIGetOnboardingCommandWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIGetOnboardingCommandWithBodyWithResponse(ctx context.Context, organizationId, contentType string, body io.Reader) (*external_connections.ExternalConnectionsAPIGetOnboardingCommandResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIGetOnboardingCommandWithBodyWithResponse", ctx, organizationId, contentType, body)
	ret0, _ := ret[0].(*external_connections.ExternalConnectionsAPIGetOnboardingCommandResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIGetOnboardingCommandWithBodyWithResponse indicates an expected call of ExternalConnectionsAPIGetOnboardingCommandWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIGetOnboardingCommandWithBodyWithResponse(ctx, organizationId, contentType, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIGetOnboardingCommandWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIGetOnboardingCommandWithBodyWithResponse), ctx, organizationId, contentType, body)
}

// ExternalConnectionsAPIGetOnboardingCommandWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIGetOnboardingCommandWithResponse(ctx context.Context, organizationId string, body external_connections.ExternalConnectionsAPIGetOnboardingCommandJSONRequestBody) (*external_connections.ExternalConnectionsAPIGetOnboardingCommandResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIGetOnboardingCommandWithResponse", ctx, organizationId, body)
	ret0, _ := ret[0].(*external_connections.ExternalConnectionsAPIGetOnboardingCommandResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIGetOnboardingCommandWithResponse indicates an expected call of ExternalConnectionsAPIGetOnboardingCommandWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIGetOnboardingCommandWithResponse(ctx, organizationId, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIGetOnboardingCommandWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIGetOnboardingCommandWithResponse), ctx, organizationId, body)
}

// ExternalConnectionsAPIListConnections mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIListConnections(ctx context.Context, organizationId string, params *external_connections.ExternalConnectionsAPIListConnectionsParams, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIListConnections", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIListConnections indicates an expected call of ExternalConnectionsAPIListConnections.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIListConnections(ctx, organizationId, params interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIListConnections", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIListConnections), varargs...)
}

// ExternalConnectionsAPIListConnectionsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIListConnectionsWithResponse(ctx context.Context, organizationId string, params *external_connections.ExternalConnectionsAPIListConnectionsParams) (*external_connections.ExternalConnectionsAPIListConnectionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIListConnectionsWithResponse", ctx, organizationId, params)
	ret0, _ := ret[0].(*external_connections.ExternalConnectionsAPIListConnectionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIListConnectionsWithResponse indicates an expected call of ExternalConnectionsAPIListConnectionsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIListConnectionsWithResponse(ctx, organizationId, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIListConnectionsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIListConnectionsWithResponse), ctx, organizationId, params)
}

// ExternalConnectionsAPIListFeatures mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIListFeatures(ctx context.Context, params *external_connections.ExternalConnectionsAPIListFeaturesParams, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIListFeatures", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIListFeatures indicates an expected call of ExternalConnectionsAPIListFeatures.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIListFeatures(ctx, params interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIListFeatures", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIListFeatures), varargs...)
}

// ExternalConnectionsAPIListFeaturesWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIListFeaturesWithResponse(ctx context.Context, params *external_connections.ExternalConnectionsAPIListFeaturesParams) (*external_connections.ExternalConnectionsAPIListFeaturesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIListFeaturesWithResponse", ctx, params)
	ret0, _ := ret[0].(*external_connections.ExternalConnectionsAPIListFeaturesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIListFeaturesWithResponse indicates an expected call of ExternalConnectionsAPIListFeaturesWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIListFeaturesWithResponse(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIListFeaturesWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIListFeaturesWithResponse), ctx, params)
}

// ExternalConnectionsAPIProvisionCastPrincipals mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIProvisionCastPrincipals(ctx context.Context, organizationId string, body external_connections.ExternalConnectionsAPIProvisionCastPrincipalsJSONRequestBody, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIProvisionCastPrincipals", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIProvisionCastPrincipals indicates an expected call of ExternalConnectionsAPIProvisionCastPrincipals.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIProvisionCastPrincipals(ctx, organizationId, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIProvisionCastPrincipals", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIProvisionCastPrincipals), varargs...)
}

// ExternalConnectionsAPIProvisionCastPrincipalsWithBody mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIProvisionCastPrincipalsWithBody(ctx context.Context, organizationId, contentType string, body io.Reader, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIProvisionCastPrincipalsWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIProvisionCastPrincipalsWithBody indicates an expected call of ExternalConnectionsAPIProvisionCastPrincipalsWithBody.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIProvisionCastPrincipalsWithBody(ctx, organizationId, contentType, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIProvisionCastPrincipalsWithBody", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIProvisionCastPrincipalsWithBody), varargs...)
}

// ExternalConnectionsAPIProvisionCastPrincipalsWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIProvisionCastPrincipalsWithBodyWithResponse(ctx context.Context, organizationId, contentType string, body io.Reader) (*external_connections.ExternalConnectionsAPIProvisionCastPrincipalsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIProvisionCastPrincipalsWithBodyWithResponse", ctx, organizationId, contentType, body)
	ret0, _ := ret[0].(*external_connections.ExternalConnectionsAPIProvisionCastPrincipalsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIProvisionCastPrincipalsWithBodyWithResponse indicates an expected call of ExternalConnectionsAPIProvisionCastPrincipalsWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIProvisionCastPrincipalsWithBodyWithResponse(ctx, organizationId, contentType, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIProvisionCastPrincipalsWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIProvisionCastPrincipalsWithBodyWithResponse), ctx, organizationId, contentType, body)
}

// ExternalConnectionsAPIProvisionCastPrincipalsWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIProvisionCastPrincipalsWithResponse(ctx context.Context, organizationId string, body external_connections.ExternalConnectionsAPIProvisionCastPrincipalsJSONRequestBody) (*external_connections.ExternalConnectionsAPIProvisionCastPrincipalsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIProvisionCastPrincipalsWithResponse", ctx, organizationId, body)
	ret0, _ := ret[0].(*external_connections.ExternalConnectionsAPIProvisionCastPrincipalsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIProvisionCastPrincipalsWithResponse indicates an expected call of ExternalConnectionsAPIProvisionCastPrincipalsWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIProvisionCastPrincipalsWithResponse(ctx, organizationId, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIProvisionCastPrincipalsWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIProvisionCastPrincipalsWithResponse), ctx, organizationId, body)
}

// ExternalConnectionsAPIUpsertConnection mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIUpsertConnection(ctx context.Context, organizationId string, body external_connections.ExternalConnectionsAPIUpsertConnectionJSONRequestBody, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIUpsertConnection", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIUpsertConnection indicates an expected call of ExternalConnectionsAPIUpsertConnection.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIUpsertConnection(ctx, organizationId, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIUpsertConnection", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIUpsertConnection), varargs...)
}

// ExternalConnectionsAPIUpsertConnectionWithBody mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIUpsertConnectionWithBody(ctx context.Context, organizationId, contentType string, body io.Reader, reqEditors ...external_connections.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, organizationId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIUpsertConnectionWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIUpsertConnectionWithBody indicates an expected call of ExternalConnectionsAPIUpsertConnectionWithBody.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIUpsertConnectionWithBody(ctx, organizationId, contentType, body interface{}, reqEditors ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, organizationId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIUpsertConnectionWithBody", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIUpsertConnectionWithBody), varargs...)
}

// ExternalConnectionsAPIUpsertConnectionWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIUpsertConnectionWithBodyWithResponse(ctx context.Context, organizationId, contentType string, body io.Reader) (*external_connections.ExternalConnectionsAPIUpsertConnectionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIUpsertConnectionWithBodyWithResponse", ctx, organizationId, contentType, body)
	ret0, _ := ret[0].(*external_connections.ExternalConnectionsAPIUpsertConnectionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIUpsertConnectionWithBodyWithResponse indicates an expected call of ExternalConnectionsAPIUpsertConnectionWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIUpsertConnectionWithBodyWithResponse(ctx, organizationId, contentType, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIUpsertConnectionWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIUpsertConnectionWithBodyWithResponse), ctx, organizationId, contentType, body)
}

// ExternalConnectionsAPIUpsertConnectionWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ExternalConnectionsAPIUpsertConnectionWithResponse(ctx context.Context, organizationId string, body external_connections.ExternalConnectionsAPIUpsertConnectionJSONRequestBody) (*external_connections.ExternalConnectionsAPIUpsertConnectionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExternalConnectionsAPIUpsertConnectionWithResponse", ctx, organizationId, body)
	ret0, _ := ret[0].(*external_connections.ExternalConnectionsAPIUpsertConnectionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExternalConnectionsAPIUpsertConnectionWithResponse indicates an expected call of ExternalConnectionsAPIUpsertConnectionWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ExternalConnectionsAPIUpsertConnectionWithResponse(ctx, organizationId, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalConnectionsAPIUpsertConnectionWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ExternalConnectionsAPIUpsertConnectionWithResponse), ctx, organizationId, body)
}

// MockResponse is a mock of Response interface.
type MockResponse struct {
	ctrl     *gomock.Controller
	recorder *MockResponseMockRecorder
}

// MockResponseMockRecorder is the mock recorder for MockResponse.
type MockResponseMockRecorder struct {
	mock *MockResponse
}

// NewMockResponse creates a new mock instance.
func NewMockResponse(ctrl *gomock.Controller) *MockResponse {
	mock := &MockResponse{ctrl: ctrl}
	mock.recorder = &MockResponseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponse) EXPECT() *MockResponseMockRecorder {
	return m.recorder
}

// GetBody mocks base method.
func (m *MockResponse) GetBody() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBody")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetBody indicates an expected call of GetBody.
func (mr *MockResponseMockRecorder) GetBody() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBody", reflect.TypeOf((*MockResponse)(nil).GetBody))
}

// Status mocks base method.
func (m *MockResponse) Status() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(string)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockResponseMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockResponse)(nil).Status))
}

// StatusCode mocks base method.
func (m *MockResponse) StatusCode() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusCode")
	ret0, _ := ret[0].(int)
	return ret0
}

// StatusCode indicates an expected call of StatusCode.
func (mr *MockResponseMockRecorder) StatusCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusCode", reflect.TypeOf((*MockResponse)(nil).StatusCode))
}
