name: Generate SDK and Docs
on:
  pull_request:
    branches: [ '*' ]
jobs:
  files-changed:
    name: detect files changed
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      generate-docs: ${{ steps.changes.outputs.generate-docs }}
      generate-sdk: ${{ steps.changes.outputs.generate-sdk }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml
  generate-sdk:
    needs: files-changed
    if: needs.files-changed.outputs.generate-sdk == 'true'
    name: Check if SDK is up to date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: 1.25.5
      - uses: actions/checkout@v6
      - name: Check SDK
        run: | 
          make generate-sdk
          if [[ -n $(git status -s) ]]
          then
            echo "SDK is not up to date, regenerate it by running 'make generate-sdk' and commit your changes."
            exit 1
          fi
  generate-docs:
    needs: files-changed
    if: needs.files-changed.outputs.generate-docs == 'true'
    name: Check if documentation is up to date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: 1.25.5
      - uses: actions/checkout@v6
      - name: Check Documentation
        run: | 
          make generate-docs
          if [[ -n $(git status -s) ]]
          then
            echo "Documentation is not up to date, regenerate it by running 'make generate-docs' and commit your changes."
            exit 1
          fi
