name: Go Tests

on:
  pull_request:
    branches: [ '*' ]
    paths-ignore:
      - '**.md'
      - '**.md.tmpl'
      - 'examples/**'
jobs:
  gotests:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Go 1.24.0
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.0'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Test
        run: make test
